In [1]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [3]:
from config import (
    CATEGORY_ROUND0_SUMMARY_PATH,
    CATEGORY_APE_ALL_SUMMARY_PATH,
    BEST_PROMPT_BY_CATEGORY_PATH,
)
from llm_utils import is_valid_prompt_instruction
from prompt_utils import get_category_meta_prompt

Using local model path: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\models\Qwen2.5-1.5B-Instruct

`torch_dtype` is deprecated! Use `dtype` instead!

In [4]:
round0_summary = pd.read_csv(CATEGORY_ROUND0_SUMMARY_PATH)

try:
    ape_summary = pd.read_csv(CATEGORY_APE_ALL_SUMMARY_PATH)
except Exception:
    ape_summary = pd.DataFrame()

print("ROUND0 SHAPE:", round0_summary.shape)
print("ROUND0 COLS:", round0_summary.columns.tolist())

print("APE SHAPE:", ape_summary.shape if not ape_summary.empty else "(0, 0)")
print("APE COLS:", ape_summary.columns.tolist() if not ape_summary.empty else [])

ROUND0 SHAPE: (55, 12)
ROUND0 COLS: ['ape_round', 'parent_prompt_id', 'subcategory', 'prompt_id', 'prompt_family', 'prompt_variant', 'prompt_text', 'mean_proxy_score', 'mean_similarity', 'mean_brevity', 'mean_target_leak', 'n_examples']
APE SHAPE: (93, 11)
APE COLS: ['ape_round', 'parent_prompt_id', 'subcategory', 'prompt_id', 'prompt_family', 'prompt_text', 'mean_proxy_score', 'mean_similarity', 'mean_brevity', 'mean_target_leak', 'selection_status']

In [5]:
required_cols = [
    "subcategory",
    "prompt_text",
    "mean_proxy_score",
    "ape_round",
    "parent_prompt_id",
    "prompt_id",
    "prompt_family",
    "prompt_variant",
]

for col in required_cols:
    if col not in round0_summary.columns:
        round0_summary[col] = pd.NA

if not ape_summary.empty:
    for col in required_cols:
        if col not in ape_summary.columns:
            ape_summary[col] = pd.NA

round0_summary = round0_summary[required_cols].copy()

if ape_summary.empty:
    combined_summary = round0_summary.copy()
else:
    ape_summary = ape_summary[required_cols].copy()
    combined_summary = pd.concat([round0_summary, ape_summary], ignore_index=True)

combined_summary["subcategory"] = combined_summary["subcategory"].fillna("").astype(str).str.strip()
combined_summary["prompt_text"] = combined_summary["prompt_text"].fillna("").astype(str).str.strip()
combined_summary["prompt_variant"] = combined_summary["prompt_variant"].fillna("").astype(str).str.strip()
combined_summary["mean_proxy_score"] = pd.to_numeric(
    combined_summary["mean_proxy_score"], errors="coerce"
).fillna(0.0)

combined_summary = combined_summary[
    (combined_summary["subcategory"] != "") &
    (combined_summary["prompt_text"] != "") &
    (combined_summary["prompt_text"].apply(is_valid_prompt_instruction))
].copy()

print("COMBINED SHAPE AFTER FILTER:", combined_summary.shape)
display(combined_summary.head(10))

COMBINED SHAPE AFTER FILTER: (145, 8)

,subcategory,prompt_text,mean_proxy_score,ape_round,parent_prompt_id,prompt_id,prompt_family,prompt_variant
0,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.613788,0,NaN,交通工具_p01,category_meta,v1_meta_base
1,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.595717,0,NaN,交通工具_p02,category_meta,v2_discriminative
2,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.566154,0,NaN,交通工具_p03,category_meta,v3_life_context
3,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.686101,0,NaN,休閒娛樂_p01,category_meta,v1_meta_base
4,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.667851,0,NaN,休閒娛樂_p03,category_meta,v3_life_context
5,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.600724,0,NaN,休閒娛樂_p02,category_meta,v2_discriminative
6,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.548430,0,NaN,動作_p03,category_meta,v3_life_context
7,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.534476,0,NaN,動作_p01,category_meta,v1_meta_base
8,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.522896,0,NaN,動作_p02,category_meta,v2_discriminative
9,動物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成...,0.697142,0,NaN,動物_p02,category_meta,v2_discriminative

In [6]:
# professor-style selection bonus
combined_summary["variant_bonus"] = 0.0

combined_summary.loc[
    combined_summary["prompt_variant"] == "v1_meta_base", "variant_bonus"
] = 0.03

combined_summary.loc[
    combined_summary["prompt_variant"] == "v2_discriminative", "variant_bonus"
] = 0.05

combined_summary.loc[
    combined_summary["prompt_variant"] == "v3_life_context", "variant_bonus"
] = 0.04

combined_summary["selection_score"] = (
    combined_summary["mean_proxy_score"] + combined_summary["variant_bonus"]
)

best_prompt_by_category_df = (
    combined_summary
    .sort_values(["subcategory", "selection_score"], ascending=[True, False])
    .groupby("subcategory", as_index=False)
    .head(1)
    .reset_index(drop=True)
)

display(best_prompt_by_category_df)

,subcategory,prompt_text,mean_proxy_score,ape_round,parent_prompt_id,prompt_id,prompt_family,prompt_variant,variant_bonus,selection_score
0,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.595717,0,NaN,交通工具_p02,category_meta,v2_discriminative,0.05,0.645717
1,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.686101,0,NaN,休閒娛樂_p01,category_meta,v1_meta_base,0.03,0.716101
2,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.548430,0,NaN,動作_p03,category_meta,v3_life_context,0.04,0.588430
3,動物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成...,0.697142,0,NaN,動物_p02,category_meta,v2_discriminative,0.05,0.747142
4,喝,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.989949,0,NaN,喝_p02,category_meta,v2_discriminative,0.05,1.039949
5,娛樂場所,描述地點的常見景象或功能，避免太抽象的描述。,0.353307,1,娛樂場所_p02,娛樂場所_ape_1_42e5edbc,category_resampled,,0.00,0.353307
6,學校,設計一組針對失語症患者的簡單、具體且容易聯想到答案的提示句列表。,0.635580,3,學校_ape_2_4f193443,學校_ape_3_e7a8d43d,category_resampled,,0.00,0.635580
7,家具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.830629,0,NaN,家具_p02,category_meta,v2_discriminative,0.05,0.880629
8,廚房用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.609120,0,NaN,廚房用品_p02,category_meta,v2_discriminative,0.05,0.659120
9,文具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.739974,0,NaN,文具_p02,category_meta,v2_discriminative,0.05,0.789974
10,服飾&配件,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.633999,0,NaN,服飾&配件_p03,category_meta,v3_life_context,0.04,0.673999
11,水果,每句提示句須精準指向該水果的專屬特徵。,0.611215,1,水果_p01,水果_ape_1_ba664d45,category_resampled,,0.00,0.611215
12,生活用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,0.586607,0,NaN,生活用品_p03,category_meta,v3_life_context,0.04,0.626607
13,調味,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.453042,0,NaN,調味_p01,category_meta,v1_meta_base,0.03,0.483042
14,輔具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.616198,0,NaN,輔具_p02,category_meta,v2_discriminative,0.05,0.666198
15,運動場所,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.460015,0,NaN,運動場所_p02,category_meta,v2_discriminative,0.05,0.510015
16,醫療場所,詢問失語症患者通常會使用哪些具體的語意提示句？,0.471432,3,醫療場所_ape_2_b433921d,醫療場所_ape_3_9ddc53ef,category_resampled,,0.00,0.471432
17,金融機構,語意提示句：「從失語症患者的角度思考，構思一句具體、簡單、容易聯想到答案的語意提示句。」,0.627863,3,金融機構_ape_2_6179ca4a,金融機構_ape_3_f495041b,category_resampled,,0.00,0.627863
18,電器用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,0.643797,0,NaN,電器用品_p01,category_meta,v1_meta_base,0.03,0.673797
19,食物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,0.721790,0,NaN,食物_p03,category_meta,v3_life_context,0.04,0.761790
20,餐具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.567202,0,NaN,餐具_p02,category_meta,v2_discriminative,0.05,0.617202

In [7]:
# manual override for weak categories
MANUAL_BEST_PROMPT_OVERRIDES = {
    "交通工具": get_category_meta_prompt("交通工具"),
    "交通場所": get_category_meta_prompt("交通場所"),
}

for subcat, prompt_text in MANUAL_BEST_PROMPT_OVERRIDES.items():
    if subcat in best_prompt_by_category_df["subcategory"].values:
        best_prompt_by_category_df.loc[
            best_prompt_by_category_df["subcategory"] == subcat,
            "prompt_text"
        ] = prompt_text
        best_prompt_by_category_df.loc[
            best_prompt_by_category_df["subcategory"] == subcat,
            "prompt_variant"
        ] = "manual_prof_override"

display(best_prompt_by_category_df)

,subcategory,prompt_text,mean_proxy_score,ape_round,parent_prompt_id,prompt_id,prompt_family,prompt_variant,variant_bonus,selection_score
0,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.595717,0,NaN,交通工具_p02,category_meta,manual_prof_override,0.05,0.645717
1,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.686101,0,NaN,休閒娛樂_p01,category_meta,v1_meta_base,0.03,0.716101
2,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.548430,0,NaN,動作_p03,category_meta,v3_life_context,0.04,0.588430
3,動物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成...,0.697142,0,NaN,動物_p02,category_meta,v2_discriminative,0.05,0.747142
4,喝,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.989949,0,NaN,喝_p02,category_meta,v2_discriminative,0.05,1.039949
5,娛樂場所,描述地點的常見景象或功能，避免太抽象的描述。,0.353307,1,娛樂場所_p02,娛樂場所_ape_1_42e5edbc,category_resampled,,0.00,0.353307
6,學校,設計一組針對失語症患者的簡單、具體且容易聯想到答案的提示句列表。,0.635580,3,學校_ape_2_4f193443,學校_ape_3_e7a8d43d,category_resampled,,0.00,0.635580
7,家具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.830629,0,NaN,家具_p02,category_meta,v2_discriminative,0.05,0.880629
8,廚房用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.609120,0,NaN,廚房用品_p02,category_meta,v2_discriminative,0.05,0.659120
9,文具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.739974,0,NaN,文具_p02,category_meta,v2_discriminative,0.05,0.789974
10,服飾&配件,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.633999,0,NaN,服飾&配件_p03,category_meta,v3_life_context,0.04,0.673999
11,水果,每句提示句須精準指向該水果的專屬特徵。,0.611215,1,水果_p01,水果_ape_1_ba664d45,category_resampled,,0.00,0.611215
12,生活用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,0.586607,0,NaN,生活用品_p03,category_meta,v3_life_context,0.04,0.626607
13,調味,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.453042,0,NaN,調味_p01,category_meta,v1_meta_base,0.03,0.483042
14,輔具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.616198,0,NaN,輔具_p02,category_meta,v2_discriminative,0.05,0.666198
15,運動場所,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.460015,0,NaN,運動場所_p02,category_meta,v2_discriminative,0.05,0.510015
16,醫療場所,詢問失語症患者通常會使用哪些具體的語意提示句？,0.471432,3,醫療場所_ape_2_b433921d,醫療場所_ape_3_9ddc53ef,category_resampled,,0.00,0.471432
17,金融機構,語意提示句：「從失語症患者的角度思考，構思一句具體、簡單、容易聯想到答案的語意提示句。」,0.627863,3,金融機構_ape_2_6179ca4a,金融機構_ape_3_f495041b,category_resampled,,0.00,0.627863
18,電器用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,0.643797,0,NaN,電器用品_p01,category_meta,v1_meta_base,0.03,0.673797
19,食物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,0.721790,0,NaN,食物_p03,category_meta,v3_life_context,0.04,0.761790
20,餐具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.567202,0,NaN,餐具_p02,category_meta,v2_discriminative,0.05,0.617202

In [8]:
#best_prompt_df.to_csv(BEST_PROMPT_PATH, index=False, encoding="utf-8-sig")

#best_prompt_text = best_prompt_df.iloc[0]["prompt_text"]
#with open(BEST_PROMPT_TXT_PATH, "w", encoding="utf-8") as f:
 #   f.write(best_prompt_text)

#print("Saved:", BEST_PROMPT_PATH)
#print("Saved:", BEST_PROMPT_TXT_PATH)

In [9]:
best_prompt_by_category_df.to_csv(
    BEST_PROMPT_BY_CATEGORY_PATH,
    index=False,
    encoding="utf-8-sig"
)
print("Saved:", BEST_PROMPT_BY_CATEGORY_PATH)

Saved: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\best_prompt_by_category.csv

In [10]:
for _, row in best_prompt_by_category_df.iterrows():
    print("=" * 100)
    print("CATEGORY:", row["subcategory"])
    print("PROMPT VARIANT:", row["prompt_variant"])
    print("MEAN PROXY SCORE:", row["mean_proxy_score"])
    print("SELECTION SCORE:", row["selection_score"])
    print("BEST PROMPT:")
    print(row["prompt_text"])
    print()

====================================================================================================
CATEGORY: 交通工具
PROMPT VARIANT: manual_prof_override
MEAN PROXY SCORE: 0.5957167913516362
SELECTION SCORE: 0.6457167913516363
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並生成具體、生活化、容易聯想到答案的提示句。

我的最終目標是幫助高齡失語症患者，透過搭乘經驗與用途線索，成功說出目標詞彙。

原則：
1. 優先描述用途、搭乘方式、常見情境。
2. 避免只描述太廣泛的移動概念。
3. 優先使用高齡者熟悉的搭車經驗與日常說法。
4. 避免太書面、太技術化的描述。

提示特徵資料集（交通工具專用）：
●用途：載人、代步、通勤、旅行、上學
●情境：在路上、停靠站牌、上下班、城市裡、出遠門
●辨識特徵：固定路線、很多人一起搭、司機開、有座位、有輪子
●熟悉場景：等車、刷卡、買票、坐著移動

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、自然、容易理解。
●盡量指向單一交通工具。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

====================================================================================================
CATEGORY: 休閒娛樂
PROMPT VARIANT: v1_meta_base
MEAN PROXY SCORE: 0.6861010606090227
SELECTION SCORE: 0.7161010606090227
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

====================================================================================================
CATEGORY: 動作
PROMPT VARIANT: v3_life_context
MEAN PROXY SCORE: 0.5484302889549645
SELECTION SCORE: 0.5884302889549645
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成具體、容易理解、方便聯想到答案的提示句。

目標是讓高齡失語症患者透過動作情境、目的或流程聯想到該動作名稱。

原則：
1. 提示句應描述做這個動作時的典型情境。
2. 可描述目的、使用工具、動作前後會發生的事情。
3. 避免直接命令患者去做該動作。
4. 避免只說太抽象的動作概念。

提示特徵資料集（動作專用）：
●情境：早上起床後、吃飯前、洗澡後、出門前
●目的：讓身體乾淨、整理自己、完成日常生活
●工具：牙刷、剪刀、指甲剪、馬桶、毛巾
●流程：先做什麼，再做什麼
●結果：變乾淨、變整齊、完成整理

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、清楚、容易理解。
●應盡量指向單一動作。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

====================================================================================================
CATEGORY: 動物
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.6971418969333172
SELECTION SCORE: 0.7471418969333172
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過外觀、叫聲、生活環境或習性聯想到該動物名稱。

原則：
1. 優先描述外觀、叫聲、移動方式或生活環境。
2. 避免過於抽象或不具辨識度的描述。
3. 每句應盡量指向單一動物。

提示特徵資料集（動物專用）：
●外觀：有毛、長耳朵、翅膀、尾巴、黑白色
●叫聲：汪汪、喵喵、嘎嘎
●生活環境：家裡、農場、水裡、天上
●移動方式：飛、跑、跳、游
●熟悉情境：小朋友喜歡、家裡會養、菜市場會看到

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需清楚、具體、容易理解。
●應具辨識度。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 喝
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.9899492859840392
SELECTION SCORE: 1.0399492859840391
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 娛樂場所
PROMPT VARIANT:
MEAN PROXY SCORE: 0.3533069521188736
SELECTION SCORE: 0.3533069521188736
BEST PROMPT:
描述地點的常見景象或功能，避免太抽象的描述。

====================================================================================================
CATEGORY: 學校
PROMPT VARIANT:
MEAN PROXY SCORE: 0.635579776763916
SELECTION SCORE: 0.635579776763916
BEST PROMPT:
設計一組針對失語症患者的簡單、具體且容易聯想到答案的提示句列表。

====================================================================================================
CATEGORY: 家具
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.8306288003921509
SELECTION SCORE: 0.880628800392151
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 廚房用品
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.609119975566864
SELECTION SCORE: 0.6591199755668641
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 文具
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.7399741053581237
SELECTION SCORE: 0.7899741053581237
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 服飾&配件
PROMPT VARIANT: v3_life_context
MEAN PROXY SCORE: 0.633999253064394
SELECTION SCORE: 0.673999253064394
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

====================================================================================================
CATEGORY: 水果
PROMPT VARIANT:
MEAN PROXY SCORE: 0.6112147157390911
SELECTION SCORE: 0.6112147157390911
BEST PROMPT:
每句提示句須精準指向該水果的專屬特徵。

====================================================================================================
CATEGORY: 生活用品
PROMPT VARIANT: v3_life_context
MEAN PROXY SCORE: 0.5866068053990602
SELECTION SCORE: 0.6266068053990602
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是幫助高齡失語症患者，透過日常使用經驗聯想到該生活用品名稱。

原則：
1. 提示句應貼近日常生活經驗。
2. 優先描述用途、外觀、放置位置或使用情境。
3. 每句須盡量指向該用品的專屬特徵。

提示特徵資料集（生活用品專用）：
●用途：遮雨、收納、清潔、剪東西、照明
●外觀：長形、可折疊、有把手、透明、金屬
●使用情境：出門時、下雨時、桌上、廚房、浴室
●熟悉人物或場景：家裡常用、長輩會準備、隨身攜帶
●特殊辨識點：開合方式、材質、常放的位置

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、明確、易理解。
●避免只說很常見但不具辨識度的功能。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

====================================================================================================
CATEGORY: 調味
PROMPT VARIANT: v1_meta_base
MEAN PROXY SCORE: 0.4530421689152717
SELECTION SCORE: 0.48304216891527174
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

====================================================================================================
CATEGORY: 輔具
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.61619799832503
SELECTION SCORE: 0.66619799832503
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 運動場所
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.4600153550505638
SELECTION SCORE: 0.5100153550505638
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

====================================================================================================
CATEGORY: 醫療場所
PROMPT VARIANT:
MEAN PROXY SCORE: 0.4714324726590088
SELECTION SCORE: 0.4714324726590088
BEST PROMPT:
詢問失語症患者通常會使用哪些具體的語意提示句？

====================================================================================================
CATEGORY: 金融機構
PROMPT VARIANT:
MEAN PROXY SCORE: 0.6278626859188079
SELECTION SCORE: 0.6278626859188079
BEST PROMPT:
語意提示句：「從失語症患者的角度思考，構思一句具體、簡單、容易聯想到答案的語意提示句。」

====================================================================================================
CATEGORY: 電器用品
PROMPT VARIANT: v1_meta_base
MEAN PROXY SCORE: 0.6437969289720058
SELECTION SCORE: 0.6737969289720058
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過功能與使用情境聯想到該電器名稱。

原則：
1. 優先描述功能、使用情境、放置位置。
2. 避免技術性過高或抽象描述。
3. 每句應盡量指向該電器的主要用途與辨識特徵。

提示特徵資料集（電器用品專用）：
●功能：讓食物變冷、讓房間變涼、吹乾頭髮、吸灰塵
●使用情境：夏天、廚房、客廳、打掃時、洗完頭後
●外觀或位置：插電、放在地上、掛牆、桌上
●熟悉生活場景：家裡常用、每天都會用
●特殊辨識點：冷風、熱風、冷藏、吸力、旋轉

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●句子需清楚具體、容易理解。
●避免太空泛的電器描述。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

====================================================================================================
CATEGORY: 食物
PROMPT VARIANT: v3_life_context
MEAN PROXY SCORE: 0.7217904212077458
SELECTION SCORE: 0.7617904212077459
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成具體、容易理解、貼近生活的提示句，幫助患者成功說出答案。

目標是讓高齡失語症患者透過熟悉的飲食經驗聯想到該食物名稱。

原則：
1. 提示句需具體、生活化、貼近日常飲食經驗。
2. 避免抽象或過於廣泛的描述。
3. 每句應盡量指向該食物的專屬特徵。

提示特徵資料集（食物專用）：
●味道與口感：甜、鹹、酥、軟、冰、熱
●外觀特徵：片狀、圓形、白色、金黃色
●用餐情境：早餐、點心、肚子不舒服時吃
●料理與食用方式：烤、煎、塗果醬、配牛奶
●熟悉人物或生活場景：早餐店、家裡餐桌、媽媽準備

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體且容易理解。
●避免太廣泛，盡量指向單一食物。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

====================================================================================================
CATEGORY: 餐具
PROMPT VARIANT: v2_discriminative
MEAN PROXY SCORE: 0.5672020435333252
SELECTION SCORE: 0.6172020435333252
BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

In [11]:
output_txt = PROJECT_ROOT / "data" / "final" / "best_prompts_by_category.txt"

with open(output_txt, "w", encoding="utf-8") as f:
    for _, row in best_prompt_by_category_df.iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"CATEGORY: {row['subcategory']}\n")
        f.write(f"PROMPT VARIANT: {row['prompt_variant']}\n")
        f.write(f"MEAN PROXY SCORE: {row['mean_proxy_score']}\n")
        f.write(f"SELECTION SCORE: {row['selection_score']}\n")
        f.write("BEST PROMPT:\n")
        f.write(str(row["prompt_text"]) + "\n\n")

print("Saved:", output_txt)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\best_prompts_by_category.txt