In [1]:
import sys
from pathlib import Path
import pandas as pd
from tqdm import tqdm

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
from config import (
    BEST_HUMAN_CUES_PATH,
    SEED_EXAMPLES_PATH,
    BEST_PROMPT_BY_CATEGORY_PATH,
    FINAL_GENERATED_CUES_BY_CATEGORY_PATH,
)
from prompt_utils import sample_demo_examples, format_demo_block
from llm_utils import generate_therapy_cue
from scoring_utils import compute_proxy_score

Using local model path: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\models\Qwen2.5-1.5B-Instruct

`torch_dtype` is deprecated! Use `dtype` instead!

In [5]:
best_human_df = pd.read_csv(BEST_HUMAN_CUES_PATH)
seed_df = pd.read_csv(SEED_EXAMPLES_PATH)

print("BEST_PROMPT_BY_CATEGORY_PATH:", BEST_PROMPT_BY_CATEGORY_PATH)
print("File exists:", BEST_PROMPT_BY_CATEGORY_PATH.exists())

best_prompt_by_category_df = pd.read_csv(BEST_PROMPT_BY_CATEGORY_PATH)

print("BEST PROMPT DF SHAPE:", best_prompt_by_category_df.shape)
display(best_prompt_by_category_df.head(20))

best_prompt_map = dict(
    zip(best_prompt_by_category_df["subcategory"], best_prompt_by_category_df["prompt_text"])
)

print("Categories with best prompts:", len(best_prompt_map))
print(sorted(best_prompt_map.keys()))

BEST_PROMPT_BY_CATEGORY_PATH: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\best_prompt_by_category.csv
File exists: True
BEST PROMPT DF SHAPE: (18, 10)

,subcategory,prompt_text,mean_proxy_score,ape_round,parent_prompt_id,prompt_id,prompt_family,prompt_variant,variant_bonus,selection_score
0,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.689594,0,NaN,交通工具_p01,category_meta,manual_prof_override,0.03,0.719594
1,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.658961,0,NaN,休閒娛樂_p01,category_meta,v1_meta_base,0.03,0.688961
2,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.591880,0,NaN,動作_p02,category_meta,v2_discriminative,0.05,0.641880
3,動物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成...,1.000000,0,NaN,動物_p02,category_meta,v2_discriminative,0.05,1.050000
4,家具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.815609,0,NaN,家具_p02,category_meta,v2_discriminative,0.05,0.865609
5,廚房用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.828295,0,NaN,廚房用品_p01,category_meta,v1_meta_base,0.03,0.858295
6,文具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.739974,0,NaN,文具_p02,category_meta,v2_discriminative,0.05,0.789974
7,服飾&配件,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.609606,0,NaN,服飾&配件_p01,category_meta,v1_meta_base,0.03,0.639606
8,水果,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標水果詞彙，並根據...,0.410725,0,NaN,水果_p03,category_meta,v3_life_context,0.04,0.450725
9,生活用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,0.616680,0,NaN,生活用品_p01,category_meta,v1_meta_base,0.03,0.646680
10,調味,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.527402,0,NaN,調味_p01,category_meta,v1_meta_base,0.03,0.557402
11,購物場所,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.390288,0,NaN,購物場所_p01,category_meta,v1_meta_base,0.03,0.420288
12,輔具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.615054,0,NaN,輔具_p03,category_meta,v3_life_context,0.04,0.655054
13,運動場所,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.460015,0,NaN,運動場所_p02,category_meta,v2_discriminative,0.05,0.510015
14,金融機構,**構思一句簡單明了、容易記住並應用於失語症治療中的提示句。**,0.627863,1,金融機構_p01,金融機構_ape_1_fc1ffac9,category_resampled,NaN,0.00,0.627863
15,電器用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,0.609818,0,NaN,電器用品_p02,category_meta,v2_discriminative,0.05,0.659818
16,食物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,0.723982,0,NaN,食物_p02,category_meta,v2_discriminative,0.05,0.773982
17,餐具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.708606,0,NaN,餐具_p01,category_meta,v1_meta_base,0.03,0.738606

Categories with best prompts: 18
['交通工具', '休閒娛樂', '動作', '動物', '家具', '廚房用品', '文具', '服飾&配件', '水果', '生活用品', '調味', '購物場所', '輔具', '運動場所', '金融機構', '電器用品', '食物', '餐具']

In [6]:
final_rows = []

for _, ex in tqdm(best_human_df.iterrows(), total=len(best_human_df), desc="Final generation by category"):
    subcategory = ex["subcategory"]

    if subcategory not in best_prompt_map:
        continue

    best_prompt_text = best_prompt_map[subcategory]

    demo_examples = sample_demo_examples(
        seed_df=seed_df,
        subcategory=subcategory,
        n_examples=3,
        random_state=42,
    )
    demo_block = format_demo_block(demo_examples)

    final_generated_cue = generate_therapy_cue(
        instruction=best_prompt_text,
        target_word=ex["target_word"],
        pos=ex["pos"],
        subcategory=subcategory,
        demo_block=demo_block,
    )

    score_dict = compute_proxy_score(
        generated_cue=final_generated_cue,
        target_word=ex["target_word"],
        reference_cue=ex["cue_text"],
    )

    final_rows.append({
        "target_word": ex["target_word"],
        "pos": ex["pos"],
        "main_category": ex["main_category"],
        "subcategory": subcategory,
        "reference_best_human_cue": ex["cue_text"],
        "best_prompt": best_prompt_text,
        "final_generated_cue": final_generated_cue,
        **score_dict,
    })

final_cues_df = pd.DataFrame(final_rows)

print("FINAL CUES SHAPE:", final_cues_df.shape)
display(final_cues_df.head(20))

Final generation by category:   0%|          | 0/130 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Final generation by category: 100%|██████████| 130/130 [03:05<00:00,  1.42s/it]

FINAL CUES SHAPE: (119, 11)

,target_word,pos,main_category,subcategory,reference_best_human_cue,best_prompt,final_generated_cue,semantic_similarity,brevity_score,target_leak_penalty,proxy_score
0,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.0,1.0,0.000000
1,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,,0.000000,0.0,1.0,0.000000
2,假牙,名詞,日常起居,輔具,剛戴上時可能會有異物感,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要定期檢查和磨損情況,0.193244,1.0,0.0,0.435271
3,傘,名詞,日常起居,生活用品,"用完後要晾乾,不然會發霉",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,需要防護，防止雨水侵入,0.365362,1.0,0.0,0.555753
4,公車,名詞,日常起居,交通工具,票價便宜,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要刷卡上車,0.353978,1.0,0.0,0.547784
5,冰淇淋,名詞,日常飲食,食物,吃起來冰涼黏稠,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,,0.000000,0.0,1.0,0.000000
6,冰箱,名詞,日常起居,電器用品,"長方形,有兩個門",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,冷凍食物、保持溫度,0.102371,1.0,0.0,0.371659
7,冷氣,名詞,日常起居,電器用品,開27度可以環保愛地球,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,,0.000000,0.0,1.0,0.000000
8,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.0,1.0,0.000000
9,削水果,動詞,日常行為,動作,通常使用在蘋果、梨子、棗子等較硬的果皮上,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,切開水果，準備飲食時,0.649515,1.0,0.0,0.754661
10,剪刀,名詞,日常起居,生活用品,大部分是塑膠手柄,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要定期磨損,保持鋒利",0.344954,1.0,0.0,0.541468
11,剪指甲,動詞,日常行為,動作,需要使用專門的小工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.0,1.0,0.000000
12,助聽器,名詞,日常起居,輔具,需要定期更換電池或充電,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,,0.000000,0.0,1.0,0.000000
13,原子筆,名詞,日常起居,文具,按一下或轉一下可推出筆芯,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,輕輕一按，啟動智慧靈感,0.628534,1.0,0.0,0.739974
14,叉子,名詞,日常起居,餐具,兒童款的XX會比較圓潤,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,,0.000000,0.0,1.0,0.000000
15,吃飯,動詞,日常行為,動作,一天三餐,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.0,1.0,0.000000
16,吐司,名詞,日常飲食,食物,拉肚子的時候會吃的,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,,0.000000,0.0,1.0,0.000000
17,吸塵器,名詞,日常起居,電器用品,分為無線與有線兩種,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,旋轉手柄、吸盤、地面、室內,0.201853,1.0,0.0,0.441297
18,吹風機,名詞,日常起居,電器用品,"部分有折疊設計,方便攜帶",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,夏天使用、廚房常見、放桌上、冷風凍食,0.232188,1.0,0.0,0.462532
19,咳嗽,動詞,日常行為,動作,會泡陳皮和柿餅茶來緩解症狀,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.0,1.0,0.000000

In [7]:
final_cues_df.to_csv(
    FINAL_GENERATED_CUES_BY_CATEGORY_PATH,
    index=False,
    encoding="utf-8-sig"
)
print("Saved:", FINAL_GENERATED_CUES_BY_CATEGORY_PATH)

Saved: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_generated_cues_by_category.csv

In [8]:
for subcat in sorted(final_cues_df["subcategory"].unique()):
    print("=" * 100)
    print("CATEGORY:", subcat)

    best_prompt_text = final_cues_df[final_cues_df["subcategory"] == subcat]["best_prompt"].iloc[0]
    print("\nBEST PROMPT:")
    print(best_prompt_text)

    print("\nTOP GENERATED CUES:")
    display(
        final_cues_df[final_cues_df["subcategory"] == subcat][
            ["target_word", "reference_best_human_cue", "final_generated_cue", "proxy_score"]
        ].sort_values("proxy_score", ascending=False).head(10)
    )

====================================================================================================
CATEGORY: 交通工具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並生成具體、生活化、容易聯想到答案的提示句。

我的最終目標是幫助高齡失語症患者，透過搭乘經驗與用途線索，成功說出目標詞彙。

原則：
1. 優先描述用途、搭乘方式、常見情境。
2. 避免只描述太廣泛的移動概念。
3. 優先使用高齡者熟悉的搭車經驗與日常說法。
4. 避免太書面、太技術化的描述。

提示特徵資料集（交通工具專用）：
●用途：載人、代步、通勤、旅行、上學
●情境：在路上、停靠站牌、上下班、城市裡、出遠門
●辨識特徵：固定路線、很多人一起搭、司機開、有座位、有輪子
●熟悉場景：等車、刷卡、買票、坐著移動

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、自然、容易理解。
●盡量指向單一交通工具。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
53           火車         需要購票搭乘,有分自由座和對號座            需要提前購買車票     0.859989
77          自行車                 運動或代步皆適合         騎行輕鬆，享受沿途風景     0.667316
44           汽車                 需要加油才能行駛             需要錢才能開動     0.651159
4            公車                     票價便宜              需要刷卡上車     0.547784
33          摩托車             需要加汽油或電力才能運行            需要牌照才能上路     0.528981
115          高鐵          透過電力驅動,行駛於專用軌道上            需要提前預約座位     0.401098

====================================================================================================
CATEGORY: 休閒娛樂

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
1          下象棋       需要理解不同棋子的移動規則才能下得好                              0.0
20          唱歌    有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏                              0.0
28          打拳               XX能提升身體平衡感                              0.0
39          散步       天氣涼爽時會更舒服,避免烈日或下雨天                              0.0
45          泡茶               選擇合適的茶具與水質                              0.0
63          登山           有可能會碰到熊,要有防熊噴霧                              0.0
64          看書             會用手翻頁或摺角作為書籤                              0.0
65         看電視           用遙控器來切換頻道或調整音量                              0.0
96          購物            節日會推出促銷活動吸引客人                              0.0
98          跳舞           與拍手、踩腳或轉圈的動作結合                              0.0

====================================================================================================
CATEGORY: 動作

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成具體、容易理解、方便聯想到答案的提示句。

目標是讓高齡失語症患者透過動作情境、目的或流程聯想到該動作名稱。

原則：
1. 提示句應描述做這個動作時的典型情境。
2. 可描述目的、使用工具、動作前後會發生的事情。
3. 避免直接命令患者去做該動作。
4. 避免只說太抽象的動作概念。

提示特徵資料集（動作專用）：
●情境：早上起床後、吃飯前、洗澡後、出門前
●目的：讓身體乾淨、整理自己、完成日常生活
●工具：牙刷、剪刀、指甲剪、馬桶、毛巾
●流程：先做什麼，再做什麼
●結果：變乾淨、變整齊、完成整理

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、清楚、容易理解。
●應盡量指向單一動作。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
9          削水果     通常使用在蘋果、梨子、棗子等較硬的果皮上          切開水果，準備飲食時     0.754661
71         穿鞋子             如果穿錯腳,會覺得不舒服            洗腳後，準備穿鞋     0.676318
34         摺衣服         有些人會用專門的板子來幫助摺整齊           整理衣物，準備上床     0.513069
23          寫字              學生上課時經常做的事情         拿起筆，在紙上寫下名字     0.483495
75         綁頭髮             需要使用特定的工具來固定        早晨起床後，梳理清爽頭發     0.398648
15          吃飯                     一天三餐                         0.000000
0          上廁所             會坐/蹲在馬桶上執行動作                         0.000000
11         剪指甲               需要使用專門的小工具                         0.000000
8           刷牙        正確的XX方式是由上往下、由內到外                         0.000000
27         打噴嚏                生病時會更頻繁發生                         0.000000

====================================================================================================
CATEGORY: 動物

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過外觀、叫聲、生活環境或習性聯想到該動物名稱。

原則：
1. 優先描述外觀、叫聲、移動方式或生活環境。
2. 避免過於抽象或不具辨識度的描述。
3. 每句應盡量指向單一動物。

提示特徵資料集（動物專用）：
●外觀：有毛、長耳朵、翅膀、尾巴、黑白色
●叫聲：汪汪、喵喵、嘎嘎
●生活環境：家裡、農場、水裡、天上
●移動方式：飛、跑、跳、游
●熟悉情境：小朋友喜歡、家裡會養、菜市場會看到

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需清楚、具體、容易理解。
●應具辨識度。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
95            貓         有時很黏人,有時愛獨處,個性多變    有時很黏人,有時愛獨處,個性多變     1.000000
94            豬                  可做成肉乾食用  有時很黏人,有時愛群居,生活在田間地     0.463859
59            牛                  可做成肉乾食用                         0.000000
61            狗               很多人家裡會養的動物                         0.000000
106           雞       吃穀物、蟲子,有時候也會啄地上的食物                         0.000000

====================================================================================================
CATEGORY: 家具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
41           桌子             吃飯時大家會圍著它坐下來       餐桌上擺放著各式各樣的餐具     0.741871
25            床            有收納空間,底下可以放東西                         0.000000
89           衣櫃             有木製、塑膠、金屬等材質                         0.000000
103          鏡子          用久會變髒,需要擦拭才能更清晰                         0.000000

====================================================================================================
CATEGORY: 廚房用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
68           砧板           表面平整,不會卡住食材或殘渣        使用時保持平穩，避免滑動     0.678283
80           菜刀            有中式、西式、切水果等種類                         0.000000
102          鍋子             料理方式不同也需不同種類                         0.000000

====================================================================================================
CATEGORY: 文具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
13         原子筆             按一下或轉一下可推出筆芯         輕輕一按，啟動智慧靈感     0.739974

====================================================================================================
CATEGORY: 服飾&配件

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
88          衣服          冬天穿太少會冷,夏天穿太多會熱             夏天穿太多会热     0.856829
90          襪子                   棉或毛的材質             冬天穿太多會冷     0.316533
24          帽子              冬天的款式有時會加內襯                         0.000000

====================================================================================================
CATEGORY: 水果

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標水果詞彙，並根據以下嚴格原則，生成語境明確、具啟發性、方便高齡者聯想的提示句，幫助患者成功說出目標詞彙。

我的最終目標是幫助高齡失語症患者，透過具體提示成功說出該水果名稱。

原則：
1. 提示句必須具體、貼近生活，符合高齡者熟悉的經驗與文化脈絡。
2. 避免抽象或模糊描述。
3. 每句提示句須精準指向該水果的專屬特徵。

提示特徵資料集（水果專用）：
●外觀特徵：顏色、形狀、大小、表面特徵
●味道或口感：甜、酸、脆、多汁
●生活場景：菜市場、水果攤、家裡切水果
●熟悉物引導：常見食用方式、誰會買、誰會吃
●特殊辨識點：是否成串、是否有籽、是否有綠蒂

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●提示句應具體、自然、容易理解。
●盡量使用最有辨識度的特徵，避免太廣泛。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
82           葡萄                 它的籽可以榨成油           它的皮上有許多小刺     0.586255
78           芒果                帶有濃郁的甜香氣味                         0.000000
79           草莓                   有綠色的蒂頭                         0.000000
84           蘋果                    可能會打蠟                         0.000000
114          香蕉                 台灣的旗山種很多                         0.000000
116          鳳梨                 切開後有特殊香氣                         0.000000

====================================================================================================
CATEGORY: 生活用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是幫助高齡失語症患者，透過日常使用經驗聯想到該生活用品名稱。

原則：
1. 提示句應貼近日常生活經驗。
2. 優先描述用途、外觀、放置位置或使用情境。
3. 每句須盡量指向該用品的專屬特徵。

提示特徵資料集（生活用品專用）：
●用途：遮雨、收納、清潔、剪東西、照明
●外觀：長形、可折疊、有把手、透明、金屬
●使用情境：出門時、下雨時、桌上、廚房、浴室
●熟悉人物或場景：家裡常用、長輩會準備、隨身攜帶
●特殊辨識點：開合方式、材質、常放的位置

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、明確、易理解。
●避免只說很常見但不具辨識度的功能。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
42          毛巾            需要定期清洗,避免細菌孳生         需要定期晾曬,防止霉變     0.834539
58          牙刷             要定期更換,不然毛會變形         需要定期更新,保持衛生     0.637938
48         洗髮精       有些標榜無矽靈,適合細軟髮或敏感頭皮       需要定期使用,保持頭髮清爽     0.619920
3            傘             用完後要晾乾,不然會發霉         需要防護，防止雨水侵入     0.555753
10          剪刀                 大部分是塑膠手柄         需要定期磨損,保持鋒利     0.541468
40          杯子                   有圓形的開口         需要拿來喝水,隨時備用     0.527300
87         衛生紙                     質地柔軟         需要隨時備份,保持乾淨     0.510694
66          眼鏡           造型有圓的、方的,也有無框的          需要保護眼睛免受疲勞     0.424674

====================================================================================================
CATEGORY: 調味

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
73            糖                 吃太多對胰臟不好           甜甜蜜蜜，調和百味     0.410908
117           鹽              在古代是非常珍貴的物品                         0.000000

====================================================================================================
CATEGORY: 購物場所

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
81         菜市場       肉攤師傅會熟練地切肉,依顧客需求分塊                              0.0
97        超級市場                 一般會播放輕音樂                              0.0

====================================================================================================
CATEGORY: 輔具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
91          護膝             適合冬天或關節炎患者使用    適合冬天或寒冷季節使用的保暖裝置     0.735489
2           假牙              剛戴上時可能會有異物感         需要定期檢查和磨損情況     0.435271
12         助聽器              需要定期更換電池或充電                         0.000000
30          拐杖            有標準型、四腳型或摺疊款式                         0.000000
83          藥盒            有些時間到會發出聲音或震動                         0.000000
99          輪椅          某些款式可折疊,方便攜帶或存放                         0.000000

====================================================================================================
CATEGORY: 運動場所

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
49         游泳池           比賽泳道通常是 50 公尺長         在陽光下嬉戲，水中暢游     0.460015
35          操場          有些設有夜間照明,方便晚間運動                         0.000000

====================================================================================================
CATEGORY: 金融機構

BEST PROMPT:
**構思一句簡單明了、容易記住並應用於失語症治療中的提示句。**

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
100          郵局         有些人會來這裡繳水電費或其他帳單    透過信件和金錢交易,提供收發服務     0.627863

====================================================================================================
CATEGORY: 電器用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過功能與使用情境聯想到該電器名稱。

原則：
1. 優先描述功能、使用情境、放置位置。
2. 避免技術性過高或抽象描述。
3. 每句應盡量指向該電器的主要用途與辨識特徵。

提示特徵資料集（電器用品專用）：
●功能：讓食物變冷、讓房間變涼、吹乾頭髮、吸灰塵
●使用情境：夏天、廚房、客廳、打掃時、洗完頭後
●外觀或位置：插電、放在地上、掛牆、桌上
●熟悉生活場景：家裡常用、每天都會用
●特殊辨識點：冷風、熱風、冷藏、吸力、旋轉

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●句子需清楚具體、容易理解。
●避免太空泛的電器描述。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
105         除濕機                  會吹出熱熱的風          冷風循環，保持空調冷     0.797478
62          瓦斯爐                    鍋子、鍋鏟            烤箱、爐火、煮飯     0.778112
55           烤箱               預熱、定時、溫度調整             讓食物快速回溫     0.741331
110          電話                    有回撥功能            手柄、聽筒、通話     0.682779
112         電風扇                  插電後即可使用        讓房子更涼快，清潔又省電     0.645629
32           插座                       通電        插電、放在桌上、廚房常見     0.635623
57          熱水瓶                  煮沸後會跳起來           手柄、溫暖、洗澡后     0.602855
108          電燈                    會連接開關        燈光柔和，適合休息時使用     0.560483
109          電視                   阿嬤打開XX        讓視頻在家中隨時隨地播放     0.462777
18          吹風機             部分有折疊設計,方便攜帶  夏天使用、廚房常見、放桌上、冷風凍食     0.462532

====================================================================================================
CATEGORY: 食物

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成具體、容易理解、貼近生活的提示句，幫助患者成功說出答案。

目標是讓高齡失語症患者透過熟悉的飲食經驗聯想到該食物名稱。

原則：
1. 提示句需具體、生活化、貼近日常飲食經驗。
2. 避免抽象或過於廣泛的描述。
3. 每句應盡量指向該食物的專屬特徵。

提示特徵資料集（食物專用）：
●味道與口感：甜、鹹、酥、軟、冰、熱
●外觀特徵：片狀、圓形、白色、金黃色
●用餐情境：早餐、點心、肚子不舒服時吃
●料理與食用方式：烤、煎、塗果醬、配牛奶
●熟悉人物或生活場景：早餐店、家裡餐桌、媽媽準備

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體且容易理解。
●避免太廣泛，盡量指向單一食物。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
118           麵                 由小麥製成的主食          一種由小麥製成的主食     0.991003
51           湯圓              一種由糯米粉製成的食品         一種甜而不咸的圓形食品     0.838449
43           水餃              麵皮包著內餡,冷凍儲存           一種小巧玲瓏的食品     0.788164
72            米                  煮後變軟可食用       一種由稻穀磨碎後製成的糧食     0.732961
107          雞排                  吃起來香脆多汁      一種外觀呈片狀、金黃色的食品     0.690983
52           漢堡                     西式餐點          一種夾生肉的快餐汉堡     0.661212
22          地瓜球              用紙袋裝,用竹籤戳著吃          一種圓形的小球狀食品     0.659005
92           豆腐                 可煎、炸、燉、炒         一種由大豆製成的凝固物     0.649650
113          飯糰                  常作為早餐食用         一種由米和水製成的主食     0.565434
54           火鍋              冬天或聚會時特別受歡迎                         0.000000

====================================================================================================
CATEGORY: 餐具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
50          湯匙        嬰兒用的特別小,邊緣圓滑,方便餵食        使用時輕拿輕放，保持平穩     0.567202
14          叉子              兒童款的XX會比較圓潤                         0.000000
69           碗     可以是陶瓷、不鏽鋼、塑膠或木頭材質製成的                         0.000000

In [ ]:
output_txt = PROJECT_ROOT / "data" / "final" / "best_prompts_and_cues_by_category.txt"

with open(output_txt, "w", encoding="utf-8") as f:
    for subcat in sorted(final_cues_df["subcategory"].unique()):
        f.write("=" * 100 + "\n")
        f.write(f"CATEGORY: {subcat}\n\n")

        best_prompt_text = final_cues_df[final_cues_df["subcategory"] == subcat]["best_prompt"].iloc[0]
        f.write("BEST PROMPT:\n")
        f.write(str(best_prompt_text) + "\n\n")

        f.write("TOP GENERATED CUES:\n")
        top_rows = final_cues_df[final_cues_df["subcategory"] == subcat].sort_values(
            "proxy_score", ascending=False
        ).head(10)

        for _, r in top_rows.iterrows():
            f.write(f"- target_word: {r['target_word']}\n")
            f.write(f"  reference_best_human_cue: {r['reference_best_human_cue']}\n")
            f.write(f"  final_generated_cue: {r['final_generated_cue']}\n")
            f.write(f"  proxy_score: {r['proxy_score']}\n\n")

print("Saved:", output_txt)

====================================================================================================
CATEGORY: 交通工具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並生成具體、生活化、容易聯想到答案的提示句。

我的最終目標是幫助高齡失語症患者，透過搭乘經驗與用途線索，成功說出目標詞彙。

原則：
1. 優先描述用途、搭乘方式、常見情境。
2. 避免只描述太廣泛的移動概念。
3. 優先使用高齡者熟悉的搭車經驗與日常說法。
4. 避免太書面、太技術化的描述。

提示特徵資料集（交通工具專用）：
●用途：載人、代步、通勤、旅行、上學
●情境：在路上、停靠站牌、上下班、城市裡、出遠門
●辨識特徵：固定路線、很多人一起搭、司機開、有座位、有輪子
●熟悉場景：等車、刷卡、買票、坐著移動

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、自然、容易理解。
●盡量指向單一交通工具。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
53           火車         需要購票搭乘,有分自由座和對號座            需要購票才能登車     0.881714
44           汽車                 需要加油才能行駛          需要找到最近的公交站     0.468300
115          高鐵          透過電力驅動,行駛於專用軌道上            需要提前預約座位     0.401098
4            公車                     票價便宜                         0.000000
33          摩托車             需要加汽油或電力才能運行                         0.000000
77          自行車                 運動或代步皆適合                         0.000000

====================================================================================================
CATEGORY: 休閒娛樂

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
63          登山           有可能會碰到熊,要有防熊噴霧        在山頂遠眺，風景盡收眼底     0.389707
1          下象棋       需要理解不同棋子的移動規則才能下得好                         0.000000
20          唱歌    有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏                         0.000000
28          打拳               XX能提升身體平衡感                         0.000000
39          散步       天氣涼爽時會更舒服,避免烈日或下雨天                         0.000000
45          泡茶               選擇合適的茶具與水質                         0.000000
64          看書             會用手翻頁或摺角作為書籤                         0.000000
65         看電視           用遙控器來切換頻道或調整音量                         0.000000
96          購物            節日會推出促銷活動吸引客人                         0.000000
98          跳舞           與拍手、踩腳或轉圈的動作結合                         0.000000

====================================================================================================
CATEGORY: 動作

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成具體、容易理解、方便聯想到答案的提示句。

目標是讓高齡失語症患者透過動作情境、目的或流程聯想到該動作名稱。

原則：
1. 提示句應描述做這個動作時的典型情境。
2. 可描述目的、使用工具、動作前後會發生的事情。
3. 避免直接命令患者去做該動作。
4. 避免只說太抽象的動作概念。

提示特徵資料集（動作專用）：
●情境：早上起床後、吃飯前、洗澡後、出門前
●目的：讓身體乾淨、整理自己、完成日常生活
●工具：牙刷、剪刀、指甲剪、馬桶、毛巾
●流程：先做什麼，再做什麼
●結果：變乾淨、變整齊、完成整理

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、清楚、容易理解。
●應盡量指向單一動作。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
9           削水果     通常使用在蘋果、梨子、棗子等較硬的果皮上          切開水果，準備早餐時     0.725776
15           吃飯                     一天三餐          早晨起床後，準備早餐     0.657877
23           寫字              學生上課時經常做的事情          準備紙和筆，開始書寫     0.578118
104          開門          轉動把手,讓進出口變暢通的動作         早晨起來，準備離開家門     0.563077
34          摺衣服         有些人會用專門的板子來幫助摺整齊           整理衣物，準備上床     0.513069
71          穿鞋子             如果穿錯腳,會覺得不舒服        早晨起床後，準備下樓散步     0.470616
19           咳嗽            會泡陳皮和柿餅茶來緩解症狀         咳嗚聲響起，開始清嗓喉     0.452312
29           拍照            光線、角度和背景會影響結果         拿起手機，捕捉美好瞬間     0.451310
0           上廁所             會坐/蹲在馬桶上執行動作                         0.000000
27          打噴嚏                生病時會更頻繁發生                         0.000000

====================================================================================================
CATEGORY: 動物

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過外觀、叫聲、生活環境或習性聯想到該動物名稱。

原則：
1. 優先描述外觀、叫聲、移動方式或生活環境。
2. 避免過於抽象或不具辨識度的描述。
3. 每句應盡量指向單一動物。

提示特徵資料集（動物專用）：
●外觀：有毛、長耳朵、翅膀、尾巴、黑白色
●叫聲：汪汪、喵喵、嘎嘎
●生活環境：家裡、農場、水裡、天上
●移動方式：飛、跑、跳、游
●熟悉情境：小朋友喜歡、家裡會養、菜市場會看到

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需清楚、具體、容易理解。
●應具辨識度。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
95            貓         有時很黏人,有時愛獨處,個性多變    有時很黏人,有時愛獨處,個性多變     1.000000
61            狗               很多人家裡會養的動物           有人家裡會養的動物     0.910908
94            豬                  可做成肉乾食用  有時在農場裡見到,嘴巴大,喜歡拱土找     0.620342
59            牛                  可做成肉乾食用          有角、黑白相間的動物     0.499735
106           雞       吃穀物、蟲子,有時候也會啄地上的食物                         0.000000

====================================================================================================
CATEGORY: 家具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
41           桌子             吃飯時大家會圍著它坐下來           圍桌而坐，共進美食     0.835351
89           衣櫃             有木製、塑膠、金屬等材質        櫃子裡放衣服，整理得整潔     0.532768
25            床            有收納空間,底下可以放東西                         0.000000
103          鏡子          用久會變髒,需要擦拭才能更清晰                         0.000000

====================================================================================================
CATEGORY: 廚房用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
68           砧板           表面平整,不會卡住食材或殘渣       光滑無棱角, 便于切割食材     0.751834
80           菜刀            有中式、西式、切水果等種類                         0.000000
102          鍋子             料理方式不同也需不同種類                         0.000000

====================================================================================================
CATEGORY: 文具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先選擇最有辨識度、最能區分其他同類詞彙的特徵，避免過於廣泛的描述。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
13         原子筆             按一下或轉一下可推出筆芯         輕輕一按，啟動智慧靈感     0.739974

====================================================================================================
CATEGORY: 服飾&配件

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
90          襪子                   棉或毛的材質             冬天穿太多會冷     0.316533
24          帽子              冬天的款式有時會加內襯                         0.000000
88          衣服          冬天穿太少會冷,夏天穿太多會熱                         0.000000

====================================================================================================
CATEGORY: 水果

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標水果詞彙，並根據以下嚴格原則，生成語境明確、具啟發性、方便高齡者聯想的提示句，幫助患者成功說出目標詞彙。

我的最終目標是幫助高齡失語症患者，透過具體提示成功說出該水果名稱。

原則：
1. 提示句必須具體、貼近生活，符合高齡者熟悉的經驗與文化脈絡。
2. 避免抽象或模糊描述。
3. 每句提示句須精準指向該水果的專屬特徵。

提示特徵資料集（水果專用）：
●外觀特徵：顏色、形狀、大小、表面特徵
●味道或口感：甜、酸、脆、多汁
●生活場景：菜市場、水果攤、家裡切水果
●熟悉物引導：常見食用方式、誰會買、誰會吃
●特殊辨識點：是否成串、是否有籽、是否有綠蒂

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●提示句應具體、自然、容易理解。
●盡量使用最有辨識度的特徵，避免太廣泛。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
116          鳳梨                 切開後有特殊香氣        聞起來像風吹過樹葉的香味     0.733466
78           芒果                帶有濃郁的甜香氣味                         0.000000
79           草莓                   有綠色的蒂頭                         0.000000
82           葡萄                 它的籽可以榨成油                         0.000000
84           蘋果                    可能會打蠟                         0.000000
114          香蕉                 台灣的旗山種很多                         0.000000

====================================================================================================
CATEGORY: 生活用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是幫助高齡失語症患者，透過日常使用經驗聯想到該生活用品名稱。

原則：
1. 提示句應貼近日常生活經驗。
2. 優先描述用途、外觀、放置位置或使用情境。
3. 每句須盡量指向該用品的專屬特徵。

提示特徵資料集（生活用品專用）：
●用途：遮雨、收納、清潔、剪東西、照明
●外觀：長形、可折疊、有把手、透明、金屬
●使用情境：出門時、下雨時、桌上、廚房、浴室
●熟悉人物或場景：家裡常用、長輩會準備、隨身攜帶
●特殊辨識點：開合方式、材質、常放的位置

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體、明確、易理解。
●避免只說很常見但不具辨識度的功能。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
42          毛巾            需要定期清洗,避免細菌孳生         需要定期晾曬,防止霉變     0.834539
58          牙刷             要定期更換,不然毛會變形         需要定期更新,保持衛生     0.637938
10          剪刀                 大部分是塑膠手柄         需要固定尺寸,方便裁切     0.625929
48         洗髮精       有些標榜無矽靈,適合細軟髮或敏感頭皮       需要定期使用,保持頭髮健康     0.595681
87         衛生紙                     質地柔軟         需要隨時準備,保持乾淨     0.509772
3            傘             用完後要晾乾,不然會發霉       需要防風防水,方便攜帶出行     0.501642
40          杯子                   有圓形的開口         需要隨時喝水,隨時拿取     0.500851
66          眼鏡           造型有圓的、方的,也有無框的        需要保護眼睛免受強光直射     0.435331

====================================================================================================
CATEGORY: 調味

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
73            糖                 吃太多對胰臟不好  透過人類的辛勤勞動,創造了美味的滋味     0.463359
117           鹽              在古代是非常珍貴的物品                         0.000000

====================================================================================================
CATEGORY: 購物場所

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
81         菜市場       肉攤師傅會熟練地切肉,依顧客需求分塊                              0.0
97        超級市場                 一般會播放輕音樂                              0.0

====================================================================================================
CATEGORY: 輔具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

補充要求：請優先使用高齡者熟悉的生活經驗、家庭情境或日常場景來設計提示句。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
99          輪椅          某些款式可折疊,方便攜帶或存放       需要定期調整位置或調節高度     0.564375
30          拐杖            有標準型、四腳型或摺疊款式       需要定期調整角度以適應地形     0.558802
12         助聽器              需要定期更換電池或充電                         0.000000
2           假牙              剛戴上時可能會有異物感                         0.000000
83          藥盒            有些時間到會發出聲音或震動                         0.000000
91          護膝             適合冬天或關節炎患者使用                         0.000000

====================================================================================================
CATEGORY: 運動場所

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
49         游泳池           比賽泳道通常是 50 公尺長         在陽光下嬉戲，水中暢游     0.460015
35          操場          有些設有夜間照明,方便晚間運動                         0.000000

====================================================================================================
CATEGORY: 金融機構

BEST PROMPT:
**構思一句簡單明了、容易記住並應用於失語症治療中的提示句。**

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
100          郵局         有些人會來這裡繳水電費或其他帳單    透過信件和金錢交易,提供收發服務     0.627863

====================================================================================================
CATEGORY: 電器用品

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並生成具體、生活化、容易聯想到答案的提示句。

目標是讓高齡失語症患者透過功能與使用情境聯想到該電器名稱。

原則：
1. 優先描述功能、使用情境、放置位置。
2. 避免技術性過高或抽象描述。
3. 每句應盡量指向該電器的主要用途與辨識特徵。

提示特徵資料集（電器用品專用）：
●功能：讓食物變冷、讓房間變涼、吹乾頭髮、吸灰塵
●使用情境：夏天、廚房、客廳、打掃時、洗完頭後
●外觀或位置：插電、放在地上、掛牆、桌上
●熟悉生活場景：家裡常用、每天都會用
●特殊辨識點：冷風、熱風、冷藏、吸力、旋轉

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●句子需清楚具體、容易理解。
●避免太空泛的電器描述。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
105         除濕機                  會吹出熱熱的風         冷風循環，保持空氣清新     0.813045
111          電鍋           內鍋、外鍋、加熱板、保溫開關         煮飯、加熱快、放餐桌上     0.813035
62          瓦斯爐                    鍋子、鍋鏟             爐火熊熊烤肉香     0.718258
110          電話                    有回撥功能           插座、聽筒、連接線     0.665092
112         電風扇                  插電後即可使用           旋轉風扇，清潔空調     0.652793
32           插座                       通電        插電、放在桌上、廚房常見     0.635623
108          電燈                    會連接開關          開晚上燈，照亮回家路     0.623248
109          電視                   阿嬤打開XX           收看節目、娛樂消遣     0.572666
55           烤箱               預熱、定時、溫度調整           爐子、烤麵包、烘培     0.540354
47          洗衣機                  會外接一根水管               手動換衣板     0.525641

====================================================================================================
CATEGORY: 食物

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成具體、容易理解、貼近生活的提示句，幫助患者成功說出答案。

目標是讓高齡失語症患者透過熟悉的飲食經驗聯想到該食物名稱。

原則：
1. 提示句需具體、生活化、貼近日常飲食經驗。
2. 避免抽象或過於廣泛的描述。
3. 每句應盡量指向該食物的專屬特徵。

提示特徵資料集（食物專用）：
●味道與口感：甜、鹹、酥、軟、冰、熱
●外觀特徵：片狀、圓形、白色、金黃色
●用餐情境：早餐、點心、肚子不舒服時吃
●料理與食用方式：烤、煎、塗果醬、配牛奶
●熟悉人物或生活場景：早餐店、家裡餐桌、媽媽準備

生成限制：
●提示句中不得出現目標詞彙。
●每句長度限於 20 個中文字以內。
●需具體且容易理解。
●避免太廣泛，盡量指向單一食物。

輸出格式：
●每次僅生成一個提示句。
●只輸出提示句本身，不要解釋。

TOP GENERATED CUES:

    target_word reference_best_human_cue final_generated_cue  proxy_score
118           麵                 由小麥製成的主食          一種由小麥製成的主食     0.991003
51           湯圓              一種由糯米粉製成的食品           一種圓形的小米食品     0.859512
93           豆花               一種用黃豆製成的甜點        一種由大豆製成的冷飲小吃     0.853154
43           水餃              麵皮包著內餡,冷凍儲存           一種扁平的小米食品     0.789745
107          雞排                  吃起來香脆多汁      一種外觀呈片狀、金黃色的食品     0.690983
92           豆腐                 可煎、炸、燉、炒            一種白色塊狀食品     0.689811
16           吐司                拉肚子的時候會吃的           一種薄脆的早餐面包     0.681471
22          地瓜球              用紙袋裝,用竹籤戳著吃        一種圓形、金黃色的小食品     0.638354
113          飯糰                  常作為早餐食用           一種由米製作的主食     0.567622
54           火鍋              冬天或聚會時特別受歡迎                         0.000000

====================================================================================================
CATEGORY: 餐具

BEST PROMPT:
你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一個簡短、具體、生活化且容易聯想到答案的提示句，不可直接說出目標詞。每次只輸出一個提示句，不要解釋。

TOP GENERATED CUES:

   target_word reference_best_human_cue final_generated_cue  proxy_score
50          湯匙        嬰兒用的特別小,邊緣圓滑,方便餵食        使用時輕拿輕放，保持平穩     0.567202
14          叉子              兒童款的XX會比較圓潤                         0.000000
69           碗     可以是陶瓷、不鏽鋼、塑膠或木頭材質製成的                         0.000000