In [2]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [3]:
from config import FINAL_GENERATED_CUES_BY_CATEGORY_PATH

In [4]:
final_cues_df = pd.read_csv(FINAL_GENERATED_CUES_BY_CATEGORY_PATH)

print("FINAL CUES SHAPE:", final_cues_df.shape)
display(final_cues_df.head(20))

FINAL CUES SHAPE: (125, 11)

,target_word,pos,main_category,subcategory,reference_best_human_cue,best_prompt,final_generated_cue,semantic_similarity,brevity_score,target_leak_penalty,proxy_score
0,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.536766,0.952381,0.0,0.661450
1,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,盤上落子，棋局起始，靜候勝負爭奪,0.531832,1.000000,0.0,0.672283
2,假牙,名詞,日常起居,輔具,剛戴上時可能會有異物感,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,NaN,0.000000,0.000000,1.0,0.000000
3,傘,名詞,日常起居,生活用品,"用完後要晾乾,不然會發霉",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要防風防水,方便攜帶出行",0.288061,1.000000,0.0,0.501642
4,公園,名詞,地點,娛樂場所,適合散步、慢跑的區域,描述地點的常見景象或功能，避免太抽象的描述。,遊樂區有秋千和沙坑，小朋友們愛玩其中,0.467798,1.000000,0.0,0.627459
5,公車,名詞,日常起居,交通工具,票價便宜,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,上車後，找到自己的座位，系好安全帶,0.283050,1.000000,0.0,0.498135
6,冰淇淋,名詞,日常飲食,食物,吃起來冰涼黏稠,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,NaN,0.000000,0.000000,1.0,0.000000
7,冰箱,名詞,日常起居,電器用品,"長方形,有兩個門",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,冷風、冷藏、旋轉、放置桌上,0.395688,1.000000,0.0,0.576982
8,冷氣,名詞,日常起居,電器用品,開27度可以環保愛地球,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,NaN,0.000000,0.000000,1.0,0.000000
9,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,NaN,0.000000,0.000000,1.0,0.000000
10,削水果,動詞,日常行為,動作,通常使用在蘋果、梨子、棗子等較硬的果皮上,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,切開水果，準備飲食時,0.649515,1.000000,0.0,0.754661
11,剪刀,名詞,日常起居,生活用品,大部分是塑膠手柄,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要定期磨損,保持鋒利",0.344954,1.000000,0.0,0.541468
12,剪指甲,動詞,日常行為,動作,需要使用專門的小工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,早晨起床後，先整理床鋪，再修剪手指甲,0.377159,1.000000,0.0,0.564011
13,助聽器,名詞,日常起居,輔具,需要定期更換電池或充電,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要定期調整音量調節旋鈕或連接線,0.414498,1.000000,0.0,0.590149
14,原子筆,名詞,日常起居,文具,按一下或轉一下可推出筆芯,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,輕輕一按，啟動智慧靈感,0.628534,1.000000,0.0,0.739974
15,叉子,名詞,日常起居,餐具,兒童款的XX會比較圓潤,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,NaN,0.000000,0.000000,1.0,0.000000
16,吃飯,動詞,日常行為,動作,一天三餐,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,早晨起床後，準備早餐，開始新的一天,0.502318,1.000000,0.0,0.651623
17,吐司,名詞,日常飲食,食物,拉肚子的時候會吃的,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,一種薄脆的面包片，通常搭配奶油或果酱食用,0.516947,1.000000,0.0,0.661863
18,吸塵器,名詞,日常起居,電器用品,分為無線與有線兩種,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,旋轉手柄、吸盤、地面,0.214906,1.000000,0.0,0.450434
19,吹風機,名詞,日常起居,電器用品,"部分有折疊設計,方便攜帶",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,夏天，厨房，挂牆，吹乾頭髮,0.326687,1.000000,0.0,0.528681

In [5]:
# keep only columns needed for final master cue table
final_cues_master_df = final_cues_df[[
    "target_word",
    "subcategory",
    "best_prompt",
    "reference_best_human_cue",
    "final_generated_cue",
    "proxy_score",
]].copy()

final_cues_master_df = final_cues_master_df.sort_values(
    ["subcategory", "proxy_score"],
    ascending=[True, False]
).reset_index(drop=True)

print("FINAL MASTER SHAPE:", final_cues_master_df.shape)
display(final_cues_master_df.head(20))

FINAL MASTER SHAPE: (125, 6)

,target_word,subcategory,best_prompt,reference_best_human_cue,final_generated_cue,proxy_score
0,火車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714
1,汽車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加油才能行駛,需要車道才能行駛,0.705243
2,自行車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109
3,高鐵,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423
4,公車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135
5,摩托車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682
6,泡茶,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611
7,下象棋,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283
8,跳舞,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932
9,唱歌,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839
10,購物,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226
11,打拳,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230
12,登山,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310
13,散步,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"天氣涼爽時會更舒服,避免烈日或下雨天",NaN,0.000000
14,看書,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,會用手翻頁或摺角作為書籤,NaN,0.000000
15,看電視,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,用遙控器來切換頻道或調整音量,NaN,0.000000
16,削水果,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661
17,洗澡,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,讓身體保持乾淨清新的動作,早晨洗漱後，感覺更清爽,0.729407
18,掃地,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,"搭配拖地效果更好,讓地板變得更潔淨",早晨起床後，拖把開始工作，清理地板,0.727245
19,上廁所,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450

In [6]:
# therapist review sheet
therapist_review_df = final_cues_master_df.copy()
therapist_review_df["manual_label"] = ""
therapist_review_df["manual_notes"] = ""

display(therapist_review_df.head(20))

,target_word,subcategory,best_prompt,reference_best_human_cue,final_generated_cue,proxy_score,manual_label,manual_notes
0,火車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714,,
1,汽車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加油才能行駛,需要車道才能行駛,0.705243,,
2,自行車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109,,
3,高鐵,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423,,
4,公車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135,,
5,摩托車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682,,
6,泡茶,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611,,
7,下象棋,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283,,
8,跳舞,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932,,
9,唱歌,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839,,
10,購物,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226,,
11,打拳,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230,,
12,登山,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310,,
13,散步,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"天氣涼爽時會更舒服,避免烈日或下雨天",NaN,0.000000,,
14,看書,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,會用手翻頁或摺角作為書籤,NaN,0.000000,,
15,看電視,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,用遙控器來切換頻道或調整音量,NaN,0.000000,,
16,削水果,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661,,
17,洗澡,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,讓身體保持乾淨清新的動作,早晨洗漱後，感覺更清爽,0.729407,,
18,掃地,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,"搭配拖地效果更好,讓地板變得更潔淨",早晨起床後，拖把開始工作，清理地板,0.727245,,
19,上廁所,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450,,

In [7]:
def build_image_prompt(target_word: str, subcategory: str) -> str:
    target_word = str(target_word).strip()
    subcategory = str(subcategory).strip()

    if subcategory == "水果":
        return f"a realistic {target_word}, single object, plain white background, high clarity"
    elif subcategory == "蔬菜":
        return f"a realistic {target_word}, single object, plain white background, high clarity"
    elif subcategory in ["動物"]:
        return f"a realistic {target_word}, single subject, clean background, high clarity"
    elif subcategory in ["交通工具"]:
        return f"a realistic {target_word}, clear full view, simple background, high clarity"
    elif subcategory in ["交通場所", "娛樂場所", "學校"]:
        return f"a realistic scene of {target_word}, simple and clear environment, not crowded, high clarity"
    elif subcategory in ["生活用品", "電器用品", "家具", "廚房用品", "文具", "服飾配件"]:
        return f"a realistic {target_word}, single main object, plain background, high clarity"
    elif subcategory in ["動作", "休閒娛樂"]:
        return f"a realistic illustration of the action or activity {target_word}, simple scene, high clarity"
    elif subcategory in ["喝", "食物"]:
        return f"a realistic {target_word}, clear food or drink presentation, plain background, high clarity"
    else:
        return f"a realistic {target_word}, single clear subject, plain background, high clarity"

In [8]:
image_generation_df = final_cues_master_df.copy()
image_generation_df["image_prompt"] = image_generation_df.apply(
    lambda row: build_image_prompt(row["target_word"], row["subcategory"]),
    axis=1
)

display(image_generation_df.head(20))

,target_word,subcategory,best_prompt,reference_best_human_cue,final_generated_cue,proxy_score,image_prompt
0,火車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714,"a realistic 火車, clear full view, simple backgr..."
1,汽車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加油才能行駛,需要車道才能行駛,0.705243,"a realistic 汽車, clear full view, simple backgr..."
2,自行車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109,"a realistic 自行車, clear full view, simple backg..."
3,高鐵,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423,"a realistic 高鐵, clear full view, simple backgr..."
4,公車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135,"a realistic 公車, clear full view, simple backgr..."
5,摩托車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682,"a realistic 摩托車, clear full view, simple backg..."
6,泡茶,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611,a realistic illustration of the action or acti...
7,下象棋,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283,a realistic illustration of the action or acti...
8,跳舞,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932,a realistic illustration of the action or acti...
9,唱歌,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839,a realistic illustration of the action or acti...
10,購物,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226,a realistic illustration of the action or acti...
11,打拳,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230,a realistic illustration of the action or acti...
12,登山,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310,a realistic illustration of the action or acti...
13,散步,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"天氣涼爽時會更舒服,避免烈日或下雨天",NaN,0.000000,a realistic illustration of the action or acti...
14,看書,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,會用手翻頁或摺角作為書籤,NaN,0.000000,a realistic illustration of the action or acti...
15,看電視,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,用遙控器來切換頻道或調整音量,NaN,0.000000,a realistic illustration of the action or acti...
16,削水果,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661,a realistic illustration of the action or acti...
17,洗澡,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,讓身體保持乾淨清新的動作,早晨洗漱後，感覺更清爽,0.729407,a realistic illustration of the action or acti...
18,掃地,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,"搭配拖地效果更好,讓地板變得更潔淨",早晨起床後，拖把開始工作，清理地板,0.727245,a realistic illustration of the action or acti...
19,上廁所,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450,a realistic illustration of the action or acti...

In [9]:
FINAL_DIR = PROJECT_ROOT / "data" / "final"

final_cues_master_path = FINAL_DIR / "final_cues_master.csv"
therapist_review_path = FINAL_DIR / "final_cues_for_therapist_review.csv"
image_generation_path = FINAL_DIR / "final_cues_for_image_generation.csv"

final_cues_master_df.to_csv(final_cues_master_path, index=False, encoding="utf-8-sig")
therapist_review_df.to_csv(therapist_review_path, index=False, encoding="utf-8-sig")
image_generation_df.to_csv(image_generation_path, index=False, encoding="utf-8-sig")

print("Saved:", final_cues_master_path)
print("Saved:", therapist_review_path)
print("Saved:", image_generation_path)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_cues_master.csv
Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_cues_for_therapist_review.csv
Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_cues_for_image_generation.csv

In [10]:
for subcat in sorted(image_generation_df["subcategory"].unique()):
    print("=" * 100)
    print("CATEGORY:", subcat)
    display(
        image_generation_df[image_generation_df["subcategory"] == subcat][[
            "target_word",
            "final_generated_cue",
            "image_prompt",
            "proxy_score"
        ]].head(10)
    )

====================================================================================================
CATEGORY: 交通工具

,target_word,final_generated_cue,image_prompt,proxy_score
0,火車,需要購票才能登車,"a realistic 火車, clear full view, simple backgr...",0.881714
1,汽車,需要車道才能行駛,"a realistic 汽車, clear full view, simple backgr...",0.705243
2,自行車,騎行方便，速度快，適合短途出行,"a realistic 自行車, clear full view, simple backg...",0.684109
3,高鐵,需要刷卡才能進站,"a realistic 高鐵, clear full view, simple backgr...",0.511423
4,公車,上車後，找到自己的座位，系好安全帶,"a realistic 公車, clear full view, simple backgr...",0.498135
5,摩托車,騎行在城市街道上，感受風吹拂臉頰,"a realistic 摩托車, clear full view, simple backg...",0.421682

====================================================================================================
CATEGORY: 休閒娛樂

,target_word,final_generated_cue,image_prompt,proxy_score
6,泡茶,將水倒入茶壺，加入紅茶包和糖，輕輕,a realistic illustration of the action or acti...,0.863611
7,下象棋,盤上落子，棋局起始，靜候勝負爭奪,a realistic illustration of the action or acti...,0.672283
8,跳舞,在空曠場地隨意扭轉身體，與同伴互動，,a realistic illustration of the action or acti...,0.655932
9,唱歌,在空蕩的房間裡唱著歌，讓心情更加愉快,a realistic illustration of the action or acti...,0.598839
10,購物,在超市裡逛逛，看看你想買什麼,a realistic illustration of the action or acti...,0.572226
11,打拳,在公園裡揮舞手臂，感受風和陽光,a realistic illustration of the action or acti...,0.457230
12,登山,在山頂遠眺，感受風景無比壯闊,a realistic illustration of the action or acti...,0.364310
13,散步,NaN,a realistic illustration of the action or acti...,0.000000
14,看書,NaN,a realistic illustration of the action or acti...,0.000000
15,看電視,NaN,a realistic illustration of the action or acti...,0.000000

====================================================================================================
CATEGORY: 動作

,target_word,final_generated_cue,image_prompt,proxy_score
16,削水果,切開水果，準備飲食時,a realistic illustration of the action or acti...,0.754661
17,洗澡,早晨洗漱後，感覺更清爽,a realistic illustration of the action or acti...,0.729407
18,掃地,早晨起床後，拖把開始工作，清理地板,a realistic illustration of the action or acti...,0.727245
19,上廁所,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,a realistic illustration of the action or acti...,0.661450
20,吃飯,早晨起床後，準備早餐，開始新的一天,a realistic illustration of the action or acti...,0.651623
21,量體溫,正確地測量自己的體溫，確保健康,a realistic illustration of the action or acti...,0.640894
22,穿鞋子,穿上鞋跟，開始新的一天,a realistic illustration of the action or acti...,0.578361
23,剪指甲,早晨起床後，先整理床鋪，再修剪手指甲,a realistic illustration of the action or acti...,0.564011
24,擦汗,在洗澡時，擦拭身上的汗水,a realistic illustration of the action or acti...,0.563916
25,喝水,早晨起床後，先喝杯水，再開始新的一天,a realistic illustration of the action or acti...,0.558572

====================================================================================================
CATEGORY: 動物

,target_word,final_generated_cue,image_prompt,proxy_score
41,貓,"有時很黏人,有時愛獨處,個性多變","a realistic 貓, single subject, clean backgroun...",1.000000
42,雞,家禽，喜欢吃谷粒和虫子，有时候也会在地面上啄,"a realistic 雞, single subject, clean backgroun...",0.848115
43,狗,汪汪叫，跑在田野上，主人家裡會養,"a realistic 狗, single subject, clean backgroun...",0.637125
44,豬,有時會拱背，有時會哼唧，喜歡在田間,"a realistic 豬, single subject, clean backgroun...",0.519763
45,牛,有頭、有角、黑白相間，常在田間地頭,"a realistic 牛, single subject, clean backgroun...",0.471185

====================================================================================================
CATEGORY: 喝

,target_word,final_generated_cue,image_prompt,proxy_score
46,紅茶,飲料店裡有售红茶,"a realistic 紅茶, clear food or drink presentati...",0.824362
47,珍珠奶茶,NaN,"a realistic 珍珠奶茶, clear food or drink presenta...",0.000000
48,豆漿,NaN,"a realistic 豆漿, clear food or drink presentati...",0.000000

====================================================================================================
CATEGORY: 娛樂場所

,target_word,final_generated_cue,image_prompt,proxy_score
49,公園,遊樂區有秋千和沙坑，小朋友們愛玩其中,"a realistic scene of 公園, simple and clear envi...",0.627459
50,電影院,NaN,"a realistic scene of 電影院, simple and clear env...",0.000000

====================================================================================================
CATEGORY: 學校

,target_word,final_generated_cue,image_prompt,proxy_score
51,圖書館,在學校裡有一個地方供學生借閱書籍，那兒通常,"a realistic scene of 圖書館, simple and clear env...",0.550394

====================================================================================================
CATEGORY: 家具

,target_word,final_generated_cue,image_prompt,proxy_score
52,桌子,圍桌而坐，共進餐食,"a realistic 桌子, single main object, plain back...",0.815609
53,床,NaN,"a realistic 床, single main object, plain backg...",0.000000
54,衣櫃,NaN,"a realistic 衣櫃, single main object, plain back...",0.000000
55,鏡子,NaN,"a realistic 鏡子, single main object, plain back...",0.000000

====================================================================================================
CATEGORY: 廚房用品

,target_word,final_generated_cue,image_prompt,proxy_score
56,砧板,使用時保持平穩，輕輕敲打,"a realistic 砧板, single main object, plain back...",0.638714
57,鍋子,使用時注意清洗，保持鍋內乾淨,"a realistic 鍋子, single main object, plain back...",0.575239
58,菜刀,使用時注意手勢和切割角度，確保安全與效果,"a realistic 菜刀, single main object, plain back...",0.391169

====================================================================================================
CATEGORY: 文具

,target_word,final_generated_cue,image_prompt,proxy_score
59,原子筆,輕輕一按，啟動智慧靈感,"a realistic 原子筆, single main object, plain bac...",0.739974

====================================================================================================
CATEGORY: 服飾&配件

,target_word,final_generated_cue,image_prompt,proxy_score
60,衣服,冬天穿厚點保暖，夏天少穿露腳趾,"a realistic 衣服, single clear subject, plain ba...",0.905983
61,襪子,冬天穿太多會累，夏天穿太少會熱,"a realistic 襪子, single clear subject, plain ba...",0.400545
62,帽子,NaN,"a realistic 帽子, single clear subject, plain ba...",0.000000

====================================================================================================
CATEGORY: 水果

,target_word,final_generated_cue,image_prompt,proxy_score
63,芒果,帶有鮮艷黃色外皮和橙色斑點,"a realistic 芒果, single object, plain white bac...",0.649279
64,鳳梨,帶有鮮艷的黃色外皮,"a realistic 鳳梨, single object, plain white bac...",0.644474
65,蘋果,會在手中形成一個圓形,"a realistic 蘋果, single object, plain white bac...",0.616357
66,草莓,帶有鮮艷紅色外皮和小巧圓潤形狀,"a realistic 草莓, single object, plain white bac...",0.612524
67,葡萄,它的皮薄而多汁，常見於夏季餐桌上,"a realistic 葡萄, single object, plain white bac...",0.503191
68,香蕉,皮膚光滑，黃色外觀，常成串販售,"a realistic 香蕉, single object, plain white bac...",0.378425

====================================================================================================
CATEGORY: 生活用品

,target_word,final_generated_cue,image_prompt,proxy_score
69,毛巾,"需要定期晾曬,防止霉變","a realistic 毛巾, single main object, plain back...",0.834539
70,牙刷,"需要定期更新,保持衛生","a realistic 牙刷, single main object, plain back...",0.637938
71,洗髮精,"需要定期使用,保持頭髮健康","a realistic 洗髮精, single main object, plain bac...",0.595681
72,剪刀,"需要定期磨損,保持鋒利","a realistic 剪刀, single main object, plain back...",0.541468
73,衛生紙,"需要隨時備份,保持乾淨","a realistic 衛生紙, single main object, plain bac...",0.510694
74,傘,"需要防風防水,方便攜帶出行","a realistic 傘, single main object, plain backg...",0.501642
75,杯子,"需要隨時喝水,保持水分","a realistic 杯子, single main object, plain back...",0.453963
76,眼鏡,需要保護眼睛免受疲勞,"a realistic 眼鏡, single main object, plain back...",0.424674

====================================================================================================
CATEGORY: 調味

,target_word,final_generated_cue,image_prompt,proxy_score
77,糖,甜美的白色塊狀物，常被放入食物中增添味道,"a realistic 糖, single clear subject, plain bac...",0.501583
78,鹽,NaN,"a realistic 鹽, single clear subject, plain bac...",0.000000

====================================================================================================
CATEGORY: 輔具

,target_word,final_generated_cue,image_prompt,proxy_score
79,輪椅,使用時調整座位高度，確保坐姿舒適,"a realistic 輪椅, single clear subject, plain ba...",0.665659
80,助聽器,需要定期調整音量調節旋鈕或連接線,"a realistic 助聽器, single clear subject, plain b...",0.590149
81,護膝,適合行走不便或活動受限的人群使用,"a realistic 護膝, single clear subject, plain ba...",0.561659
82,拐杖,需要定期檢查和調節松緊程度,"a realistic 拐杖, single clear subject, plain ba...",0.559645
83,藥盒,需要定期檢查密封性，保持藥物干凈,"a realistic 藥盒, single clear subject, plain ba...",0.404716
84,假牙,NaN,"a realistic 假牙, single clear subject, plain ba...",0.000000

====================================================================================================
CATEGORY: 運動場所

,target_word,final_generated_cue,image_prompt,proxy_score
85,游泳池,在陽光下嬉戲，水中暢游,"a realistic 游泳池, single clear subject, plain b...",0.460015
86,操場,NaN,"a realistic 操場, single clear subject, plain ba...",0.000000

====================================================================================================
CATEGORY: 醫療場所

,target_word,final_generated_cue,image_prompt,proxy_score
87,藥局,詢問失語症患者通常會使用哪些具體的語意提示,"a realistic 藥局, single clear subject, plain ba...",0.527630
88,醫院,詢問失語症患者通常會使用哪些具體的語意提示,"a realistic 醫院, single clear subject, plain ba...",0.415235

====================================================================================================
CATEGORY: 金融機構

,target_word,final_generated_cue,image_prompt,proxy_score
89,郵局,透過信件和金錢交易，提供收發服務,"a realistic 郵局, single clear subject, plain ba...",0.627863

====================================================================================================
CATEGORY: 電器用品

,target_word,final_generated_cue,image_prompt,proxy_score
90,熱水瓶,蓋上蓋子，倒滿冷水，開始煮沸,"a realistic 熱水瓶, single main object, plain bac...",0.906737
91,除濕機,冷風直吹，除濕效果佳,"a realistic 除濕機, single main object, plain bac...",0.842393
92,電鍋,煮飯、加熱食物、炊事工具,"a realistic 電鍋, single main object, plain back...",0.840463
93,瓦斯爐,火鍋、調味料、煮飯,"a realistic 瓦斯爐, single main object, plain bac...",0.736919
94,電風扇,吹風、清潔、擺放桌面,"a realistic 電風扇, single main object, plain bac...",0.724218
95,電話,手柄、連接線、插座,"a realistic 電話, single main object, plain back...",0.656177
96,插座,插電、放在桌上、廚房常見,"a realistic 插座, single main object, plain back...",0.635623
97,冰箱,冷風、冷藏、旋轉、放置桌上,"a realistic 冰箱, single main object, plain back...",0.576982
98,電燈,壁挂式、暖光、晚上使用,"a realistic 電燈, single main object, plain back...",0.569337
99,吹風機,夏天，厨房，挂牆，吹乾頭髮,"a realistic 吹風機, single main object, plain bac...",0.528681

====================================================================================================
CATEGORY: 食物

,target_word,final_generated_cue,image_prompt,proxy_score
106,麵,一種由小麥製成的主食,"a realistic 麵, clear food or drink presentatio...",0.991003
107,漢堡,一種肉質鮮嫩多汁的食物,"a realistic 漢堡, clear food or drink presentati...",0.819035
108,湯圓,一種甜而不咸的小圓形食品,"a realistic 湯圓, clear food or drink presentati...",0.818176
109,水餃,一種皮薄馅大的食物,"a realistic 水餃, clear food or drink presentati...",0.788069
110,米,一種由稻穀磨碎後加水蒸煮而成的主食,"a realistic 米, clear food or drink presentatio...",0.756786
111,豆花,一種由大豆製成的冷飲，通常搭配冰糖和薄荷,"a realistic 豆花, clear food or drink presentati...",0.741191
112,豆腐,一種由黄豆製成的塊狀食品,"a realistic 豆腐, clear food or drink presentati...",0.729688
113,雞排,一種外觀呈片狀、金黃色的食品,"a realistic 雞排, clear food or drink presentati...",0.690983
114,牛肉麵,一種紅色、長條形、略帶彈性的主食,"a realistic 牛肉麵, clear food or drink presentat...",0.684537
115,吐司,一種薄脆的面包片，通常搭配奶油或果酱食用,"a realistic 吐司, clear food or drink presentati...",0.661863

====================================================================================================
CATEGORY: 餐具

,target_word,final_generated_cue,image_prompt,proxy_score
122,湯匙,使用時輕拿輕放，保持平穩,"a realistic 湯匙, single clear subject, plain ba...",0.567202
123,叉子,NaN,"a realistic 叉子, single clear subject, plain ba...",0.000000
124,碗,NaN,"a realistic 碗, single clear subject, plain bac...",0.000000