In [1]:
import sys
from pathlib import Path
import pandas as pd
from tqdm import tqdm
import torch
from diffusers import StableDiffusionXLPipeline
from PIL import Image

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
FINAL_DIR = PROJECT_ROOT / "data" / "final"
IMAGE_INPUT_PATH = FINAL_DIR / "final_cues_for_image_generation.csv"

RAW_IMAGE_DIR = PROJECT_ROOT / "results" / "generated_images_raw"
MOBILE_IMAGE_DIR = PROJECT_ROOT / "results" / "generated_images_mobile"

RAW_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
MOBILE_IMAGE_DIR.mkdir(parents=True, exist_ok=True)

print("IMAGE INPUT PATH:", IMAGE_INPUT_PATH)
print("RAW IMAGE DIR:", RAW_IMAGE_DIR)
print("MOBILE IMAGE DIR:", MOBILE_IMAGE_DIR)

IMAGE INPUT PATH: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_cues_for_image_generation.csv
RAW IMAGE DIR: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\results\generated_images_raw
MOBILE IMAGE DIR: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\results\generated_images_mobile

In [3]:
image_generation_df = pd.read_csv(IMAGE_INPUT_PATH)

print("IMAGE GENERATION DF SHAPE:", image_generation_df.shape)
display(image_generation_df.head(20))

IMAGE GENERATION DF SHAPE: (125, 7)

,target_word,subcategory,best_prompt,reference_best_human_cue,final_generated_cue,proxy_score,image_prompt
0,火車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714,"a realistic 火車, clear full view, simple backgr..."
1,汽車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加油才能行駛,需要車道才能行駛,0.705243,"a realistic 汽車, clear full view, simple backgr..."
2,自行車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109,"a realistic 自行車, clear full view, simple backg..."
3,高鐵,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423,"a realistic 高鐵, clear full view, simple backgr..."
4,公車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135,"a realistic 公車, clear full view, simple backgr..."
5,摩托車,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682,"a realistic 摩托車, clear full view, simple backg..."
6,泡茶,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611,a realistic illustration of the action or acti...
7,下象棋,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283,a realistic illustration of the action or acti...
8,跳舞,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932,a realistic illustration of the action or acti...
9,唱歌,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839,a realistic illustration of the action or acti...
10,購物,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226,a realistic illustration of the action or acti...
11,打拳,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230,a realistic illustration of the action or acti...
12,登山,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310,a realistic illustration of the action or acti...
13,散步,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,"天氣涼爽時會更舒服,避免烈日或下雨天",NaN,0.000000,a realistic illustration of the action or acti...
14,看書,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,會用手翻頁或摺角作為書籤,NaN,0.000000,a realistic illustration of the action or acti...
15,看電視,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,用遙控器來切換頻道或調整音量,NaN,0.000000,a realistic illustration of the action or acti...
16,削水果,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661,a realistic illustration of the action or acti...
17,洗澡,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,讓身體保持乾淨清新的動作,早晨洗漱後，感覺更清爽,0.729407,a realistic illustration of the action or acti...
18,掃地,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,"搭配拖地效果更好,讓地板變得更潔淨",早晨起床後，拖把開始工作，清理地板,0.727245,a realistic illustration of the action or acti...
19,上廁所,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450,a realistic illustration of the action or acti...

In [4]:
SDXL_LOCAL_MODEL_PATH = r"C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\models\sdxl-base-1.0"

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

print("DEVICE:", device)
print("DTYPE:", dtype)
print("MODEL PATH:", SDXL_LOCAL_MODEL_PATH)

pipe = StableDiffusionXLPipeline.from_pretrained(
    SDXL_LOCAL_MODEL_PATH,
    torch_dtype=dtype,
    local_files_only=True,
    use_safetensors=True,
)

if device == "cuda":
    pipe = pipe.to("cuda")
else:
    pipe.enable_model_cpu_offload()

print("SDXL pipeline loaded successfully.")

DEVICE: cuda
DTYPE: torch.float16
MODEL PATH: C:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\models\sdxl-base-1.0

Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/196 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/517 [00:00<?, ?it/s]

SDXL pipeline loaded successfully.

In [5]:
def safe_filename(text: str) -> str:
    text = str(text).strip()
    bad_chars = ['\\', '/', ':', '*', '?', '"', '<', '>', '|']
    for ch in bad_chars:
        text = text.replace(ch, "_")
    return text


def build_negative_prompt(subcategory: str) -> str:
    return (
        "blurry, low quality, distorted, extra objects, cluttered background, "
        "text, watermark, logo, cropped, duplicate, messy scene"
    )


def generate_raw_image(
    prompt: str,
    negative_prompt: str,
    output_path: Path,
    seed: int = 42,
    width: int = 768,
    height: int = 768,
    num_inference_steps: int = 30,
    guidance_scale: float = 7.0,
):
    generator = torch.Generator(device=device).manual_seed(seed)

    image = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        width=width,
        height=height,
        num_inference_steps=num_inference_steps,
        guidance_scale=guidance_scale,
        generator=generator,
    ).images[0]

    image.save(output_path)
    return output_path


def export_mobile_image(raw_image_path: Path, mobile_image_path: Path, size=(512, 512), quality=90):
    img = Image.open(raw_image_path).convert("RGB")
    img = img.resize(size, Image.LANCZOS)
    img.save(mobile_image_path, format="JPEG", quality=quality, optimize=True)
    return mobile_image_path

In [6]:
test_df = image_generation_df.head(5).copy()
display(test_df[["target_word", "subcategory", "final_generated_cue", "image_prompt"]])

,target_word,subcategory,final_generated_cue,image_prompt
0,火車,交通工具,需要購票才能登車,"a realistic 火車, clear full view, simple backgr..."
1,汽車,交通工具,需要車道才能行駛,"a realistic 汽車, clear full view, simple backgr..."
2,自行車,交通工具,騎行方便，速度快，適合短途出行,"a realistic 自行車, clear full view, simple backg..."
3,高鐵,交通工具,需要刷卡才能進站,"a realistic 高鐵, clear full view, simple backgr..."
4,公車,交通工具,上車後，找到自己的座位，系好安全帶,"a realistic 公車, clear full view, simple backgr..."

In [7]:
test_rows = []

for _, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Generating TEST images"):
    target_word = row["target_word"]
    subcategory = row["subcategory"]
    final_generated_cue = row["final_generated_cue"]
    image_prompt = row["image_prompt"]

    raw_subcat_dir = RAW_IMAGE_DIR / safe_filename(subcategory)
    mobile_subcat_dir = MOBILE_IMAGE_DIR / safe_filename(subcategory)

    raw_subcat_dir.mkdir(parents=True, exist_ok=True)
    mobile_subcat_dir.mkdir(parents=True, exist_ok=True)

    raw_image_path = raw_subcat_dir / f"{safe_filename(target_word)}.png"
    mobile_image_path = mobile_subcat_dir / f"{safe_filename(target_word)}.jpg"

    generation_status = "pending"
    error_message = ""

    try:
        negative_prompt = build_negative_prompt(subcategory)

        generate_raw_image(
            prompt=image_prompt,
            negative_prompt=negative_prompt,
            output_path=raw_image_path,
            seed=42,
            width=768,
            height=768,
            num_inference_steps=30,
            guidance_scale=7.0,
        )

        export_mobile_image(
            raw_image_path=raw_image_path,
            mobile_image_path=mobile_image_path,
            size=(512, 512),
            quality=90,
        )

        generation_status = "success"

    except Exception as e:
        generation_status = "failed"
        error_message = str(e)

    test_rows.append({
        "target_word": target_word,
        "subcategory": subcategory,
        "final_generated_cue": final_generated_cue,
        "image_prompt": image_prompt,
        "raw_image_path": str(raw_image_path),
        "mobile_image_path": str(mobile_image_path),
        "generation_status": generation_status,
        "error_message": error_message,
    })

test_results_df = pd.DataFrame(test_rows)

print("TEST RESULTS SHAPE:", test_results_df.shape)
display(test_results_df)

Generating TEST images:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

c:\Users\804\anaconda3\envs\aphasia_ape\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py:748: FutureWarning: `upcast_vae` is deprecated and will be removed in version 1.0.0. `upcast_vae` is deprecated. Please use `pipe.vae.to(torch.float32)`. For more details, please refer to: https://github.com/huggingface/diffusers/pull/12619#issue-3606633695.
  deprecate(
Generating TEST images:  20%|██        | 1/5 [00:13<00:55, 13.86s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating TEST images:  40%|████      | 2/5 [00:26<00:39, 13.32s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating TEST images:  60%|██████    | 3/5 [00:39<00:26, 13.08s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating TEST images:  80%|████████  | 4/5 [00:52<00:13, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating TEST images: 100%|██████████| 5/5 [01:05<00:00, 13.09s/it]

TEST RESULTS SHAPE: (5, 8)

,target_word,subcategory,final_generated_cue,image_prompt,raw_image_path,mobile_image_path,generation_status,error_message
0,火車,交通工具,需要購票才能登車,"a realistic 火車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
1,汽車,交通工具,需要車道才能行駛,"a realistic 汽車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
2,自行車,交通工具,騎行方便，速度快，適合短途出行,"a realistic 自行車, clear full view, simple backg...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
3,高鐵,交通工具,需要刷卡才能進站,"a realistic 高鐵, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
4,公車,交通工具,上車後，找到自己的座位，系好安全帶,"a realistic 公車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,

In [8]:
print("Successful test images:", (test_results_df["generation_status"] == "success").sum())
print("Failed test images:", (test_results_df["generation_status"] == "failed").sum())

Successful test images: 5
Failed test images: 0

In [9]:
image_rows = []

for _, row in tqdm(image_generation_df.iterrows(), total=len(image_generation_df), desc="Generating FULL images"):
    target_word = row["target_word"]
    subcategory = row["subcategory"]
    final_generated_cue = row["final_generated_cue"]
    image_prompt = row["image_prompt"]

    raw_subcat_dir = RAW_IMAGE_DIR / safe_filename(subcategory)
    mobile_subcat_dir = MOBILE_IMAGE_DIR / safe_filename(subcategory)

    raw_subcat_dir.mkdir(parents=True, exist_ok=True)
    mobile_subcat_dir.mkdir(parents=True, exist_ok=True)

    raw_image_path = raw_subcat_dir / f"{safe_filename(target_word)}.png"
    mobile_image_path = mobile_subcat_dir / f"{safe_filename(target_word)}.jpg"

    generation_status = "pending"
    error_message = ""

    try:
        negative_prompt = build_negative_prompt(subcategory)

        generate_raw_image(
            prompt=image_prompt,
            negative_prompt=negative_prompt,
            output_path=raw_image_path,
            seed=42,
            width=768,
            height=768,
            num_inference_steps=30,
            guidance_scale=7.0,
        )

        export_mobile_image(
            raw_image_path=raw_image_path,
            mobile_image_path=mobile_image_path,
            size=(512, 512),
            quality=90,
        )

        generation_status = "success"

    except Exception as e:
        generation_status = "failed"
        error_message = str(e)

    image_rows.append({
        "target_word": target_word,
        "subcategory": subcategory,
        "final_generated_cue": final_generated_cue,
        "image_prompt": image_prompt,
        "raw_image_path": str(raw_image_path),
        "mobile_image_path": str(mobile_image_path),
        "generation_status": generation_status,
        "error_message": error_message,
    })

image_results_df = pd.DataFrame(image_rows)

print("IMAGE RESULTS SHAPE:", image_results_df.shape)
display(image_results_df.head(20))

Generating FULL images:   0%|          | 0/125 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

c:\Users\804\anaconda3\envs\aphasia_ape\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py:748: FutureWarning: `upcast_vae` is deprecated and will be removed in version 1.0.0. `upcast_vae` is deprecated. Please use `pipe.vae.to(torch.float32)`. For more details, please refer to: https://github.com/huggingface/diffusers/pull/12619#issue-3606633695.
  deprecate(
Generating FULL images:   1%|          | 1/125 [00:13<27:04, 13.10s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   2%|▏         | 2/125 [00:25<26:35, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   2%|▏         | 3/125 [00:38<26:15, 12.91s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   3%|▎         | 4/125 [00:51<26:04, 12.93s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   4%|▍         | 5/125 [01:04<25:56, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   5%|▍         | 6/125 [01:17<25:44, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   6%|▌         | 7/125 [01:30<25:32, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   6%|▋         | 8/125 [01:43<25:16, 12.96s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   7%|▋         | 9/125 [01:56<25:04, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   8%|▊         | 10/125 [02:09<24:52, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:   9%|▉         | 11/125 [02:22<24:38, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  10%|▉         | 12/125 [02:35<24:25, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  10%|█         | 13/125 [02:48<24:16, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  11%|█         | 14/125 [03:01<23:57, 12.95s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  12%|█▏        | 15/125 [03:14<23:43, 12.94s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  13%|█▎        | 16/125 [03:27<23:30, 12.94s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  14%|█▎        | 17/125 [03:40<23:17, 12.94s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  14%|█▍        | 18/125 [03:53<23:05, 12.95s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  15%|█▌        | 19/125 [04:06<22:52, 12.95s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  16%|█▌        | 20/125 [04:19<22:37, 12.93s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  17%|█▋        | 21/125 [04:32<22:24, 12.92s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  18%|█▊        | 22/125 [04:44<22:10, 12.92s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  18%|█▊        | 23/125 [04:57<21:59, 12.94s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  19%|█▉        | 24/125 [05:10<21:48, 12.95s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  20%|██        | 25/125 [05:23<21:35, 12.95s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  21%|██        | 26/125 [05:36<21:23, 12.96s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  22%|██▏       | 27/125 [05:49<21:10, 12.97s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  22%|██▏       | 28/125 [06:02<20:58, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  23%|██▎       | 29/125 [06:15<20:46, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  24%|██▍       | 30/125 [06:28<20:33, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  25%|██▍       | 31/125 [06:41<20:20, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  26%|██▌       | 32/125 [06:54<20:08, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  26%|██▋       | 33/125 [07:07<19:58, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  27%|██▋       | 34/125 [07:21<19:48, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  28%|██▊       | 35/125 [07:34<19:37, 13.08s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  29%|██▉       | 36/125 [07:47<19:19, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  30%|██▉       | 37/125 [08:00<19:05, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  30%|███       | 38/125 [08:13<18:52, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  31%|███       | 39/125 [08:26<18:38, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  32%|███▏      | 40/125 [08:39<18:25, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  33%|███▎      | 41/125 [08:52<18:10, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  34%|███▎      | 42/125 [09:05<17:57, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  34%|███▍      | 43/125 [09:18<17:45, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  35%|███▌      | 44/125 [09:30<17:31, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  36%|███▌      | 45/125 [09:44<17:21, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  37%|███▋      | 46/125 [09:57<17:08, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  38%|███▊      | 47/125 [10:10<16:58, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  38%|███▊      | 48/125 [10:23<16:45, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  39%|███▉      | 49/125 [10:36<16:30, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  40%|████      | 50/125 [10:49<16:16, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  41%|████      | 51/125 [11:02<16:02, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  42%|████▏     | 52/125 [11:15<15:49, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  42%|████▏     | 53/125 [11:28<15:36, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  43%|████▎     | 54/125 [11:41<15:23, 13.00s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  44%|████▍     | 55/125 [11:54<15:09, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  45%|████▍     | 56/125 [12:07<14:55, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  46%|████▌     | 57/125 [12:20<14:42, 12.98s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  46%|████▋     | 58/125 [12:33<14:30, 13.00s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  47%|████▋     | 59/125 [12:46<14:18, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  48%|████▊     | 60/125 [12:59<14:05, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  49%|████▉     | 61/125 [13:12<13:53, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  50%|████▉     | 62/125 [13:25<13:40, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  50%|█████     | 63/125 [13:38<13:27, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  51%|█████     | 64/125 [13:51<13:13, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  52%|█████▏    | 65/125 [14:04<13:01, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  53%|█████▎    | 66/125 [14:17<12:48, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  54%|█████▎    | 67/125 [14:30<12:35, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  54%|█████▍    | 68/125 [14:43<12:22, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  55%|█████▌    | 69/125 [14:56<12:10, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  56%|█████▌    | 70/125 [15:09<11:57, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  57%|█████▋    | 71/125 [15:22<11:44, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  58%|█████▊    | 72/125 [15:35<11:31, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  58%|█████▊    | 73/125 [15:48<11:18, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  59%|█████▉    | 74/125 [16:01<11:05, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  60%|██████    | 75/125 [16:14<10:51, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  61%|██████    | 76/125 [16:27<10:40, 13.07s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  62%|██████▏   | 77/125 [16:41<10:28, 13.10s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  62%|██████▏   | 78/125 [16:54<10:14, 13.08s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  63%|██████▎   | 79/125 [17:07<09:59, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  64%|██████▍   | 80/125 [17:20<09:47, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  65%|██████▍   | 81/125 [17:33<09:35, 13.07s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  66%|██████▌   | 82/125 [17:46<09:21, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  66%|██████▋   | 83/125 [17:59<09:08, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  67%|██████▋   | 84/125 [18:12<08:55, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  68%|██████▊   | 85/125 [18:25<08:40, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  69%|██████▉   | 86/125 [18:38<08:27, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  70%|██████▉   | 87/125 [18:51<08:16, 13.07s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  70%|███████   | 88/125 [19:04<08:02, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  71%|███████   | 89/125 [19:17<07:49, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  72%|███████▏  | 90/125 [19:30<07:36, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  73%|███████▎  | 91/125 [19:43<07:23, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  74%|███████▎  | 92/125 [19:56<07:10, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  74%|███████▍  | 93/125 [20:09<06:57, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  75%|███████▌  | 94/125 [20:22<06:44, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  76%|███████▌  | 95/125 [20:35<06:31, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  77%|███████▋  | 96/125 [20:48<06:18, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  78%|███████▊  | 97/125 [21:01<06:04, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  78%|███████▊  | 98/125 [21:14<05:51, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  79%|███████▉  | 99/125 [21:27<05:38, 13.01s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  80%|████████  | 100/125 [21:40<05:24, 13.00s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  81%|████████  | 101/125 [21:53<05:11, 12.99s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  82%|████████▏ | 102/125 [22:06<04:59, 13.00s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  82%|████████▏ | 103/125 [22:19<04:46, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  83%|████████▎ | 104/125 [22:32<04:33, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  84%|████████▍ | 105/125 [22:45<04:20, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  85%|████████▍ | 106/125 [22:59<04:08, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  86%|████████▌ | 107/125 [23:12<03:55, 13.09s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  86%|████████▋ | 108/125 [23:25<03:42, 13.07s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  87%|████████▋ | 109/125 [23:38<03:28, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  88%|████████▊ | 110/125 [23:51<03:15, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  89%|████████▉ | 111/125 [24:04<03:02, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  90%|████████▉ | 112/125 [24:17<02:49, 13.02s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  90%|█████████ | 113/125 [24:30<02:36, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  91%|█████████ | 114/125 [24:43<02:23, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  92%|█████████▏| 115/125 [24:56<02:10, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  93%|█████████▎| 116/125 [25:09<01:57, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  94%|█████████▎| 117/125 [25:22<01:44, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  94%|█████████▍| 118/125 [25:35<01:31, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  95%|█████████▌| 119/125 [25:48<01:18, 13.06s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  96%|█████████▌| 120/125 [26:01<01:05, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  97%|█████████▋| 121/125 [26:14<00:52, 13.03s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  98%|█████████▊| 122/125 [26:27<00:39, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  98%|█████████▊| 123/125 [26:40<00:26, 13.04s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images:  99%|█████████▉| 124/125 [26:53<00:13, 13.05s/it]

  0%|          | 0/30 [00:00<?, ?it/s]

Generating FULL images: 100%|██████████| 125/125 [27:06<00:00, 13.02s/it]

IMAGE RESULTS SHAPE: (125, 8)

,target_word,subcategory,final_generated_cue,image_prompt,raw_image_path,mobile_image_path,generation_status,error_message
0,火車,交通工具,需要購票才能登車,"a realistic 火車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
1,汽車,交通工具,需要車道才能行駛,"a realistic 汽車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
2,自行車,交通工具,騎行方便，速度快，適合短途出行,"a realistic 自行車, clear full view, simple backg...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
3,高鐵,交通工具,需要刷卡才能進站,"a realistic 高鐵, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
4,公車,交通工具,上車後，找到自己的座位，系好安全帶,"a realistic 公車, clear full view, simple backgr...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
5,摩托車,交通工具,騎行在城市街道上，感受風吹拂臉頰,"a realistic 摩托車, clear full view, simple backg...",c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
6,泡茶,休閒娛樂,將水倒入茶壺，加入紅茶包和糖，輕輕,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
7,下象棋,休閒娛樂,盤上落子，棋局起始，靜候勝負爭奪,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
8,跳舞,休閒娛樂,在空曠場地隨意扭轉身體，與同伴互動，,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
9,唱歌,休閒娛樂,在空蕩的房間裡唱著歌，讓心情更加愉快,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
10,購物,休閒娛樂,在超市裡逛逛，看看你想買什麼,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
11,打拳,休閒娛樂,在公園裡揮舞手臂，感受風和陽光,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
12,登山,休閒娛樂,在山頂遠眺，感受風景無比壯闊,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
13,散步,休閒娛樂,NaN,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
14,看書,休閒娛樂,NaN,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
15,看電視,休閒娛樂,NaN,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
16,削水果,動作,切開水果，準備飲食時,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
17,洗澡,動作,早晨洗漱後，感覺更清爽,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
18,掃地,動作,早晨起床後，拖把開始工作，清理地板,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,
19,上廁所,動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,a realistic illustration of the action or acti...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...,success,

In [10]:
generated_image_results_path = FINAL_DIR / "generated_image_results.csv"
image_results_df.to_csv(generated_image_results_path, index=False, encoding="utf-8-sig")

print("Saved:", generated_image_results_path)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\generated_image_results.csv

In [11]:
mobile_export_df = image_results_df[image_results_df["generation_status"] == "success"].copy()

mobile_export_df = mobile_export_df[[
    "target_word",
    "subcategory",
    "final_generated_cue",
    "mobile_image_path",
]].copy()

mobile_export_df = mobile_export_df.rename(columns={
    "mobile_image_path": "image_path"
})

mobile_export_path = FINAL_DIR / "mobile_ready_cue_image_package.csv"
mobile_export_df.to_csv(mobile_export_path, index=False, encoding="utf-8-sig")

print("Saved:", mobile_export_path)
display(mobile_export_df.head(20))

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\mobile_ready_cue_image_package.csv

,target_word,subcategory,final_generated_cue,image_path
0,火車,交通工具,需要購票才能登車,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,汽車,交通工具,需要車道才能行駛,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,自行車,交通工具,騎行方便，速度快，適合短途出行,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,高鐵,交通工具,需要刷卡才能進站,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,公車,交通工具,上車後，找到自己的座位，系好安全帶,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,摩托車,交通工具,騎行在城市街道上，感受風吹拂臉頰,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,泡茶,休閒娛樂,將水倒入茶壺，加入紅茶包和糖，輕輕,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,下象棋,休閒娛樂,盤上落子，棋局起始，靜候勝負爭奪,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,跳舞,休閒娛樂,在空曠場地隨意扭轉身體，與同伴互動，,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,唱歌,休閒娛樂,在空蕩的房間裡唱著歌，讓心情更加愉快,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
10,購物,休閒娛樂,在超市裡逛逛，看看你想買什麼,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
11,打拳,休閒娛樂,在公園裡揮舞手臂，感受風和陽光,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
12,登山,休閒娛樂,在山頂遠眺，感受風景無比壯闊,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
13,散步,休閒娛樂,NaN,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
14,看書,休閒娛樂,NaN,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
15,看電視,休閒娛樂,NaN,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
16,削水果,動作,切開水果，準備飲食時,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
17,洗澡,動作,早晨洗漱後，感覺更清爽,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
18,掃地,動作,早晨起床後，拖把開始工作，清理地板,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
19,上廁所,動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [12]:
success_df = image_results_df[image_results_df["generation_status"] == "success"].copy()
failed_df = image_results_df[image_results_df["generation_status"] == "failed"].copy()

print("Successful images:", len(success_df))
print("Failed images:", len(failed_df))

if len(failed_df) > 0:
    display(failed_df.head(20))

Successful images: 125
Failed images: 0