In [1]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
FINAL_DIR = PROJECT_ROOT / "data" / "final"

BEST_PROMPT_PATH = FINAL_DIR / "best_prompt_by_category.csv"
FINAL_CUES_PATH = FINAL_DIR / "final_generated_cues_by_category.csv"
MOBILE_PACKAGE_PATH = FINAL_DIR / "mobile_ready_cue_image_package.csv"

print("BEST_PROMPT_PATH:", BEST_PROMPT_PATH)
print("FINAL_CUES_PATH:", FINAL_CUES_PATH)
print("MOBILE_PACKAGE_PATH:", MOBILE_PACKAGE_PATH)

BEST_PROMPT_PATH: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\best_prompt_by_category.csv
FINAL_CUES_PATH: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_generated_cues_by_category.csv
MOBILE_PACKAGE_PATH: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\mobile_ready_cue_image_package.csv

In [3]:
best_prompt_df = pd.read_csv(BEST_PROMPT_PATH)
final_cues_df = pd.read_csv(FINAL_CUES_PATH)
mobile_package_df = pd.read_csv(MOBILE_PACKAGE_PATH)

print("best_prompt_df:", best_prompt_df.shape)
print("final_cues_df:", final_cues_df.shape)
print("mobile_package_df:", mobile_package_df.shape)

display(best_prompt_df.head(10))
display(final_cues_df.head(10))
display(mobile_package_df.head(10))

best_prompt_df: (21, 10)
final_cues_df: (125, 11)
mobile_package_df: (125, 4)

,subcategory,prompt_text,mean_proxy_score,ape_round,parent_prompt_id,prompt_id,prompt_family,prompt_variant,variant_bonus,selection_score
0,交通工具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,0.595717,0,NaN,交通工具_p02,category_meta,manual_prof_override,0.05,0.645717
1,休閒娛樂,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.686101,0,NaN,休閒娛樂_p01,category_meta,v1_meta_base,0.03,0.716101
2,動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,0.548430,0,NaN,動作_p03,category_meta,v3_life_context,0.04,0.588430
3,動物,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動物詞彙，並生成...,0.697142,0,NaN,動物_p02,category_meta,v2_discriminative,0.05,0.747142
4,喝,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.989949,0,NaN,喝_p02,category_meta,v2_discriminative,0.05,1.039949
5,娛樂場所,描述地點的常見景象或功能，避免太抽象的描述。,0.353307,1,娛樂場所_p02,娛樂場所_ape_1_42e5edbc,category_resampled,NaN,0.00,0.353307
6,學校,設計一組針對失語症患者的簡單、具體且容易聯想到答案的提示句列表。,0.635580,3,學校_ape_2_4f193443,學校_ape_3_e7a8d43d,category_resampled,NaN,0.00,0.635580
7,家具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.830629,0,NaN,家具_p02,category_meta,v2_discriminative,0.05,0.880629
8,廚房用品,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.609120,0,NaN,廚房用品_p02,category_meta,v2_discriminative,0.05,0.659120
9,文具,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,0.739974,0,NaN,文具_p02,category_meta,v2_discriminative,0.05,0.789974

,target_word,pos,main_category,subcategory,reference_best_human_cue,best_prompt,final_generated_cue,semantic_similarity,brevity_score,target_leak_penalty,proxy_score
0,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.536766,0.952381,0.0,0.661450
1,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,盤上落子，棋局起始，靜候勝負爭奪,0.531832,1.000000,0.0,0.672283
2,假牙,名詞,日常起居,輔具,剛戴上時可能會有異物感,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,NaN,0.000000,0.000000,1.0,0.000000
3,傘,名詞,日常起居,生活用品,"用完後要晾乾,不然會發霉",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要防風防水,方便攜帶出行",0.288061,1.000000,0.0,0.501642
4,公園,名詞,地點,娛樂場所,適合散步、慢跑的區域,描述地點的常見景象或功能，避免太抽象的描述。,遊樂區有秋千和沙坑，小朋友們愛玩其中,0.467798,1.000000,0.0,0.627459
5,公車,名詞,日常起居,交通工具,票價便宜,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,上車後，找到自己的座位，系好安全帶,0.283050,1.000000,0.0,0.498135
6,冰淇淋,名詞,日常飲食,食物,吃起來冰涼黏稠,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,NaN,0.000000,0.000000,1.0,0.000000
7,冰箱,名詞,日常起居,電器用品,"長方形,有兩個門",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,冷風、冷藏、旋轉、放置桌上,0.395688,1.000000,0.0,0.576982
8,冷氣,名詞,日常起居,電器用品,開27度可以環保愛地球,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,NaN,0.000000,0.000000,1.0,0.000000
9,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,NaN,0.000000,0.000000,1.0,0.000000

,target_word,subcategory,final_generated_cue,image_path
0,火車,交通工具,需要購票才能登車,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,汽車,交通工具,需要車道才能行駛,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,自行車,交通工具,騎行方便，速度快，適合短途出行,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,高鐵,交通工具,需要刷卡才能進站,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,公車,交通工具,上車後，找到自己的座位，系好安全帶,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,摩托車,交通工具,騎行在城市街道上，感受風吹拂臉頰,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,泡茶,休閒娛樂,將水倒入茶壺，加入紅茶包和糖，輕輕,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,下象棋,休閒娛樂,盤上落子，棋局起始，靜候勝負爭奪,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,跳舞,休閒娛樂,在空曠場地隨意扭轉身體，與同伴互動，,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,唱歌,休閒娛樂,在空蕩的房間裡唱著歌，讓心情更加愉快,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [4]:
for df in [best_prompt_df, final_cues_df, mobile_package_df]:
    for col in df.columns:
        if df[col].dtype == object:
            df[col] = df[col].fillna("").astype(str).str.strip()

In [5]:
best_prompt_keep = [c for c in [
    "subcategory",
    "prompt_variant",
    "mean_proxy_score",
    "selection_score",
    "prompt_text"
] if c in best_prompt_df.columns]

best_prompt_merge_df = best_prompt_df[best_prompt_keep].copy()
best_prompt_merge_df = best_prompt_merge_df.rename(columns={
    "prompt_text": "best_prompt_full",
    "mean_proxy_score": "best_prompt_score"
})

final_demo_df = final_cues_df.merge(
    best_prompt_merge_df,
    on="subcategory",
    how="left"
)

print("After merging best prompts:", final_demo_df.shape)
display(final_demo_df.head(10))

After merging best prompts: (125, 15)

,target_word,pos,main_category,subcategory,reference_best_human_cue,best_prompt,final_generated_cue,semantic_similarity,brevity_score,target_leak_penalty,proxy_score,prompt_variant,best_prompt_score,selection_score,best_prompt_full
0,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.536766,0.952381,0.0,0.661450,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...
1,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,盤上落子，棋局起始，靜候勝負爭奪,0.531832,1.000000,0.0,0.672283,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...
2,假牙,名詞,日常起居,輔具,剛戴上時可能會有異物感,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,,0.000000,0.000000,1.0,0.000000,v2_discriminative,0.616198,0.666198,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...
3,傘,名詞,日常起居,生活用品,"用完後要晾乾,不然會發霉",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要防風防水,方便攜帶出行",0.288061,1.000000,0.0,0.501642,v3_life_context,0.586607,0.626607,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...
4,公園,名詞,地點,娛樂場所,適合散步、慢跑的區域,描述地點的常見景象或功能，避免太抽象的描述。,遊樂區有秋千和沙坑，小朋友們愛玩其中,0.467798,1.000000,0.0,0.627459,,0.353307,0.353307,描述地點的常見景象或功能，避免太抽象的描述。
5,公車,名詞,日常起居,交通工具,票價便宜,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,上車後，找到自己的座位，系好安全帶,0.283050,1.000000,0.0,0.498135,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...
6,冰淇淋,名詞,日常飲食,食物,吃起來冰涼黏稠,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,,0.000000,0.000000,1.0,0.000000,v3_life_context,0.721790,0.761790,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...
7,冰箱,名詞,日常起居,電器用品,"長方形,有兩個門",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,冷風、冷藏、旋轉、放置桌上,0.395688,1.000000,0.0,0.576982,v1_meta_base,0.643797,0.673797,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...
8,冷氣,名詞,日常起居,電器用品,開27度可以環保愛地球,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,,0.000000,0.000000,1.0,0.000000,v1_meta_base,0.643797,0.673797,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...
9,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.000000,1.0,0.000000,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...

In [6]:
final_demo_df = final_demo_df.merge(
    mobile_package_df[["target_word", "subcategory", "image_path"]],
    on=["target_word", "subcategory"],
    how="left"
)

print("After merging image paths:", final_demo_df.shape)
display(final_demo_df.head(10))

After merging image paths: (125, 16)

,target_word,pos,main_category,subcategory,reference_best_human_cue,best_prompt,final_generated_cue,semantic_similarity,brevity_score,target_leak_penalty,proxy_score,prompt_variant,best_prompt_score,selection_score,best_prompt_full,image_path
0,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.536766,0.952381,0.0,0.661450,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,盤上落子，棋局起始，靜候勝負爭奪,0.531832,1.000000,0.0,0.672283,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,假牙,名詞,日常起居,輔具,剛戴上時可能會有異物感,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,,0.000000,0.000000,1.0,0.000000,v2_discriminative,0.616198,0.666198,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,傘,名詞,日常起居,生活用品,"用完後要晾乾,不然會發霉",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,"需要防風防水,方便攜帶出行",0.288061,1.000000,0.0,0.501642,v3_life_context,0.586607,0.626607,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標生活用品詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,公園,名詞,地點,娛樂場所,適合散步、慢跑的區域,描述地點的常見景象或功能，避免太抽象的描述。,遊樂區有秋千和沙坑，小朋友們愛玩其中,0.467798,1.000000,0.0,0.627459,,0.353307,0.353307,描述地點的常見景象或功能，避免太抽象的描述。,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,公車,名詞,日常起居,交通工具,票價便宜,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,上車後，找到自己的座位，系好安全帶,0.283050,1.000000,0.0,0.498135,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,冰淇淋,名詞,日常飲食,食物,吃起來冰涼黏稠,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,,0.000000,0.000000,1.0,0.000000,v3_life_context,0.721790,0.761790,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標食物詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,冰箱,名詞,日常起居,電器用品,"長方形,有兩個門",你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,冷風、冷藏、旋轉、放置桌上,0.395688,1.000000,0.0,0.576982,v1_meta_base,0.643797,0.673797,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,冷氣,名詞,日常起居,電器用品,開27度可以環保愛地球,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,,0.000000,0.000000,1.0,0.000000,v1_meta_base,0.643797,0.673797,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標電器用品詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,,0.000000,0.000000,1.0,0.000000,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [7]:
final_demo_export_df = final_demo_df[[
    "target_word",
    "pos",
    "main_category",
    "subcategory",
    "reference_best_human_cue",
    "final_generated_cue",
    "proxy_score",
    "semantic_similarity",
    "brevity_score",
    "target_leak_penalty",
    "prompt_variant",
    "best_prompt_score",
    "selection_score",
    "best_prompt_full",
    "image_path",
]].copy()

final_demo_export_df = final_demo_export_df.sort_values(
    ["subcategory", "target_word"],
    ascending=[True, True]
).reset_index(drop=True)

print("FINAL DEMO EXPORT SHAPE:", final_demo_export_df.shape)
display(final_demo_export_df.head(20))

FINAL DEMO EXPORT SHAPE: (125, 15)

,target_word,pos,main_category,subcategory,reference_best_human_cue,final_generated_cue,proxy_score,semantic_similarity,brevity_score,target_leak_penalty,prompt_variant,best_prompt_score,selection_score,best_prompt_full,image_path
0,公車,名詞,日常起居,交通工具,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135,0.283050,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,摩托車,名詞,日常起居,交通工具,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682,0.173832,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,汽車,名詞,日常起居,交通工具,需要加油才能行駛,需要車道才能行駛,0.705243,0.578918,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,火車,名詞,日常起居,交通工具,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714,0.831019,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,自行車,名詞,日常起居,交通工具,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109,0.548727,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,高鐵,名詞,日常起居,交通工具,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423,0.302032,1.000000,0.0,manual_prof_override,0.595717,0.645717,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,下象棋,動詞,日常活動,休閒娛樂,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283,0.531832,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,唱歌,動詞,日常活動,休閒娛樂,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839,0.426913,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,打拳,動詞,日常活動,休閒娛樂,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230,0.224615,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,散步,動詞,日常活動,休閒娛樂,"天氣涼爽時會更舒服,避免烈日或下雨天",,0.000000,0.000000,0.000000,1.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
10,泡茶,動詞,日常活動,休閒娛樂,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611,0.805158,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
11,登山,動詞,日常活動,休閒娛樂,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310,0.091871,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
12,看書,動詞,日常活動,休閒娛樂,會用手翻頁或摺角作為書籤,,0.000000,0.000000,0.000000,1.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
13,看電視,動詞,日常活動,休閒娛樂,用遙控器來切換頻道或調整音量,,0.000000,0.000000,0.000000,1.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
14,購物,動詞,日常活動,休閒娛樂,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226,0.388894,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
15,跳舞,動詞,日常活動,休閒娛樂,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932,0.508474,1.000000,0.0,v1_meta_base,0.686101,0.716101,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
16,上廁所,動詞,日常行為,動作,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450,0.536766,0.952381,0.0,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
17,刷牙,動詞,日常行為,動作,正確的XX方式是由上往下、由內到外,,0.000000,0.000000,0.000000,1.0,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
18,削水果,動詞,日常行為,動作,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661,0.649515,1.000000,0.0,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
19,剪指甲,動詞,日常行為,動作,需要使用專門的小工具,早晨起床後，先整理床鋪，再修剪手指甲,0.564011,0.377159,1.000000,0.0,v3_life_context,0.548430,0.588430,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [8]:
final_demo_package_path = FINAL_DIR / "final_demo_package.csv"
final_demo_export_df.to_csv(final_demo_package_path, index=False, encoding="utf-8-sig")

print("Saved:", final_demo_package_path)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_demo_package.csv

In [9]:
mobile_app_export_df = final_demo_export_df[[
    "target_word",
    "subcategory",
    "final_generated_cue",
    "image_path",
]].copy()

mobile_app_export_path = FINAL_DIR / "mobile_app_export.csv"
mobile_app_export_df.to_csv(mobile_app_export_path, index=False, encoding="utf-8-sig")

print("Saved:", mobile_app_export_path)
display(mobile_app_export_df.head(20))

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\mobile_app_export.csv

,target_word,subcategory,final_generated_cue,image_path
0,公車,交通工具,上車後，找到自己的座位，系好安全帶,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,摩托車,交通工具,騎行在城市街道上，感受風吹拂臉頰,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,汽車,交通工具,需要車道才能行駛,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,火車,交通工具,需要購票才能登車,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,自行車,交通工具,騎行方便，速度快，適合短途出行,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,高鐵,交通工具,需要刷卡才能進站,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,下象棋,休閒娛樂,盤上落子，棋局起始，靜候勝負爭奪,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,唱歌,休閒娛樂,在空蕩的房間裡唱著歌，讓心情更加愉快,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,打拳,休閒娛樂,在公園裡揮舞手臂，感受風和陽光,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,散步,休閒娛樂,,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
10,泡茶,休閒娛樂,將水倒入茶壺，加入紅茶包和糖，輕輕,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
11,登山,休閒娛樂,在山頂遠眺，感受風景無比壯闊,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
12,看書,休閒娛樂,,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
13,看電視,休閒娛樂,,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
14,購物,休閒娛樂,在超市裡逛逛，看看你想買什麼,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
15,跳舞,休閒娛樂,在空曠場地隨意扭轉身體，與同伴互動，,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
16,上廁所,動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
17,刷牙,動作,,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
18,削水果,動作,切開水果，準備飲食時,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
19,剪指甲,動作,早晨起床後，先整理床鋪，再修剪手指甲,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [10]:
professor_review_df = final_demo_export_df[[
    "target_word",
    "subcategory",
    "reference_best_human_cue",
    "final_generated_cue",
    "proxy_score",
    "best_prompt_full",
    "image_path",
]].copy()

professor_review_path = FINAL_DIR / "professor_review_package.csv"
professor_review_df.to_csv(professor_review_path, index=False, encoding="utf-8-sig")

print("Saved:", professor_review_path)
display(professor_review_df.head(20))

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\professor_review_package.csv

,target_word,subcategory,reference_best_human_cue,final_generated_cue,proxy_score,best_prompt_full,image_path
0,公車,交通工具,票價便宜,上車後，找到自己的座位，系好安全帶,0.498135,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
1,摩托車,交通工具,需要加汽油或電力才能運行,騎行在城市街道上，感受風吹拂臉頰,0.421682,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
2,汽車,交通工具,需要加油才能行駛,需要車道才能行駛,0.705243,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
3,火車,交通工具,"需要購票搭乘,有分自由座和對號座",需要購票才能登車,0.881714,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
4,自行車,交通工具,運動或代步皆適合,騎行方便，速度快，適合短途出行,0.684109,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
5,高鐵,交通工具,"透過電力驅動,行駛於專用軌道上",需要刷卡才能進站,0.511423,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標交通工具詞彙，並...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
6,下象棋,休閒娛樂,需要理解不同棋子的移動規則才能下得好,盤上落子，棋局起始，靜候勝負爭奪,0.672283,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
7,唱歌,休閒娛樂,"有時會搭配樂器,如吉他、鋼琴或卡拉OK伴奏",在空蕩的房間裡唱著歌，讓心情更加愉快,0.598839,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
8,打拳,休閒娛樂,XX能提升身體平衡感,在公園裡揮舞手臂，感受風和陽光,0.457230,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
9,散步,休閒娛樂,"天氣涼爽時會更舒服,避免烈日或下雨天",,0.000000,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
10,泡茶,休閒娛樂,選擇合適的茶具與水質,將水倒入茶壺，加入紅茶包和糖，輕輕,0.863611,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
11,登山,休閒娛樂,"有可能會碰到熊,要有防熊噴霧",在山頂遠眺，感受風景無比壯闊,0.364310,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
12,看書,休閒娛樂,會用手翻頁或摺角作為書籤,,0.000000,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
13,看電視,休閒娛樂,用遙控器來切換頻道或調整音量,,0.000000,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
14,購物,休閒娛樂,節日會推出促銷活動吸引客人,在超市裡逛逛，看看你想買什麼,0.572226,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
15,跳舞,休閒娛樂,與拍手、踩腳或轉圈的動作結合,在空曠場地隨意扭轉身體，與同伴互動，,0.655932,你是一位專門為高齡失語症患者設計語言治療提示句的專家。請根據目標詞彙最具辨識度的特徵，生成一...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
16,上廁所,動作,會坐/蹲在馬桶上執行動作,在離馬桶稍遠的地方準備好紙巾和毛巾，然後輕,0.661450,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
17,刷牙,動作,正確的XX方式是由上往下、由內到外,,0.000000,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
18,削水果,動作,通常使用在蘋果、梨子、棗子等較硬的果皮上,切開水果，準備飲食時,0.754661,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...
19,剪指甲,動作,需要使用專門的小工具,早晨起床後，先整理床鋪，再修剪手指甲,0.564011,你是一位專門為高齡失語症患者設計語言治療提示句的專家。你的任務是接收一個目標動作詞彙，並生成...,c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Gene...

In [ ]:
summary_txt_path = FINAL_DIR / "final_demo_summary.txt"

with open(summary_txt_path, "w", encoding="utf-8") as f:
    f.write("FINAL DEMO PACKAGE SUMMARY\n")
    f.write("=" * 100 + "\n\n")

    for subcat in sorted(final_demo_export_df["subcategory"].unique()):
        f.write("=" * 100 + "\n")
        f.write(f"CATEGORY: {subcat}\n\n")

        sub_df = final_demo_export_df[final_demo_export_df["subcategory"] == subcat].copy()

        best_prompt_text = sub_df["best_prompt_full"].iloc[0] if len(sub_df) > 0 else ""
        f.write("BEST PROMPT:\n")
        f.write(str(best_prompt_text) + "\n\n")

        f.write("TOP ITEMS:\n")
        top_rows = sub_df.sort_values("proxy_score", ascending=False).head(10)

        for _, r in top_rows.iterrows():
            f.write(f"- target_word: {r['target_word']}\n")
            f.write(f"  reference_best_human_cue: {r['reference_best_human_cue']}\n")
            f.write(f"  final_generated_cue: {r['final_generated_cue']}\n")
            f.write(f"  proxy_score: {r['proxy_score']}\n")
            f.write(f"  image_path: {r['image_path']}\n\n")

print("Saved:", summary_txt_path)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\final\final_demo_summary.txt

In [12]:
print("All final exports created successfully.")
print()
print("1. final_demo_package.csv")
print("2. mobile_app_export.csv")
print("3. professor_review_package.csv")
print("4. final_demo_summary.txt")

All final exports created successfully.

1. final_demo_package.csv
2. mobile_app_export.csv
3. professor_review_package.csv
4. final_demo_summary.txt